import React,{useState,useEffect} from 'react';
import './initial-landing.css';
import {siteLinks} from '../../frontend/site-links.js';
import {CAPS} from './protocol-data.mjs';
const sites=siteLinks(location.href),APP=sites.member,REPO=sites.whitepaper,REVIEW=sites.whitepaper;
const format=n=>new Intl.NumberFormat('en-US',{maximumFractionDigits:0}).format(n);
function Mark(){return <span className="brand-mark" aria-hidden="true"><i/><i/><i/></span>}
function External({href,children,className=''}){return <a className={className} href={href} target="_blank" rel="noopener noreferrer">{children}</a>}
function Eyebrow({n,children}){return <div className="eyebrow"><span>{n}</span>{children}</div>}
function Tree({left,right}){return <svg className="tree" viewBox="0 0 520 290" role="img" aria-label={`A binary position with ${left} left units and ${right} right units`}><g fill="none" stroke="#3c5548" strokeWidth="1.5"><path d="M260 62V102H130V144M260 102H390V144M130 184V217H65V242M130 217H195V242M390 184V217H325V242M390 217H455V242"/></g><g fill="#15241c" stroke="#526f5c"><rect x="229" y="10" width="62" height="60" rx="16"/><rect x="99" y="134" width="62" height="58" rx="14"/><rect x="359" y="134" width="62" height="58" rx="14"/></g><g fill="#b2ffd0"><circle cx="260" cy="33" r="7"/><path d="M246 54c0-15 28-15 28 0z"/><circle cx="130" cy="158" r="7"/><path d="M116 179c0-15 28-15 28 0z"/><circle cx="390" cy="158" r="7"/><path d="M376 179c0-15 28-15 28 0z"/></g>{[65,195,325,455].map(x=><g key={x}><circle cx={x} cy="255" r="15" fill="#15241c" stroke="#526f5c"/><circle cx={x} cy="255" r="4" fill="#91b49d"/></g>)}<g fill="#dae9df" fontSize="14" fontFamily="Arial"><text x="130" y="120" textAnchor="middle">LEFT · {left}</text><text x="390" y="120" textAnchor="middle">RIGHT · {right}</text></g></svg>}
function CurveChart({mode}){const buy=mode==='buy';return <svg viewBox="0 0 610 250" className="curve-chart" role="img" aria-label={buy?'Illustrative rising purchase curve, not a price forecast':'Illustrative declining redemption curve, not a price forecast'}><defs><linearGradient id="chartFill" x1="0" y1="0" x2="0" y2="1"><stop stopColor="#b2ffd0" stopOpacity=".25"/><stop offset="1" stopColor="#b2ffd0" stopOpacity="0"/></linearGradient></defs>{[45,95,145,195].map(y=><path key={y} d={`M20 ${y}H590`} stroke="#243c2e" strokeDasharray="3 6"/>)}<path d={buy?'M20 213 C200 205 390 180 590 28 V225H20Z':'M20 28 C180 150 360 206 590 213 V225H20Z'} fill="url(#chartFill)"/><path d={buy?'M20 213 C200 205 390 180 590 28':'M20 28 C180 150 360 206 590 213'} stroke="#b2ffd0" strokeWidth="3" fill="none"/><circle cx="590" cy={buy?28:213} r="5" fill="#b2ffd0"/><text x="20" y="245" fill="#99ada2" fontSize="12">START</text><text x="590" y="245" textAnchor="end" fill="#99ada2" fontSize="12">{buy?'MORE TOKENS MINTED':'MORE TOKENS REDEEMED'}</text></svg>}
const faq=[
 ['What is FTI Protocol?','FTI is an experimental membership and token system on BNB Smart Chain testnet. One contract manages binary placement and funded rewards. A second manages FTI purchases, redemptions, reserves and separate support funds.'],
 ['Does membership guarantee income?','No. Membership units are not a promise of principal repayment or income. Rewards depend on eligible points and available funding. The current contracts distribute participant-funded pools; they do not generate an external investment yield.'],
 ['How does the binary plan match volume?','Each position has a left and right branch. Raw matched points are the smaller of the two available volumes. Rank and protection level cap the points paid in an epoch. Unpaid matched volume is retained for later settlement. Paid points require funded backing.'],
 ['Why can a token sale be unavailable?','Sales depend on available funding, minimum output and contract limits. Gross sales up to 500 test USD are exempt from ordinary sale caps; larger sales have reserve and hourly limits. There is no time lock.'],
 ['Is the protocol independently audited?','No. Diagnostic tests are available, but independent auditing is not complete. Local checks do not prove safety on the public network.'],
 ['How do staged purchases work?','Purchases are recalculated in 500 test USD steps at each new reserve quote. Wallet allowances and the 128-step transaction limit apply. Larger purchases need multiple transactions.'],
 ['Can I use real money here?','This release is for test assets only. Use BNB testnet and test tokens. MockUSD is not a real stablecoin, and an FTI testnet balance has no promised monetary value.']
];
export function InitialLanding(){
 const [menu,setMenu]=useState(false),[units,setUnits]=useState(1),[left,setLeft]=useState(30),[right,setRight]=useState(12),[rank,setRank]=useState(1),[level,setLevel]=useState(0),[mode,setMode]=useState('buy'),[opened,setOpened]=useState(0),[copied,setCopied]=useState(false);
 const caps=CAPS;
 const [token,setToken]=useState(null);
 useEffect(()=>{const controller=new AbortController();fetch("/api/config",{signal:controller.signal}).then(r=>{if(!r.ok)throw Error("Config unavailable");return r.json()}).then(c=>{if(c.chainId===97&&/^0x[0-9a-fA-F]{40}$/.test(c.token)&&!/^0x0{40}$/.test(c.token))setToken(c.token)}).catch(()=>{});return()=>controller.abort()},[]);
 const raw=Math.min(left,right),paid=Math.min(raw,caps[level][rank]);
 useEffect(()=>{function escape(e){if(e.key==='Escape')setMenu(false)}document.addEventListener('keydown',escape);return()=>document.removeEventListener('keydown',escape)},[]);
 async function copy(){try{if(!token)return;await navigator.clipboard.writeText(token);setCopied(true);setTimeout(()=>setCopied(false),2200)}catch{setCopied(false)}}
 return <div className="initial-landing" dir="ltr" lang="en"><a className="skip" href="#main">Skip to content</a><header><div className="nav wrap"><a className="logo" href="#"><Mark/><span>FTI<span className="logo-light"> Protocol</span></span></a><nav className={menu?'open':''} aria-label="Main navigation">{[['Protocol','protocol'],['Binary plan','binary'],['Token','token'],['Development','development']].map(([label,id])=><a key={id} href={'#'+id} onClick={()=>setMenu(false)}>{label}</a>)}</nav><External href={APP} className="button small nav-cta">Explore testnet</External><button className="menu" aria-expanded={menu} aria-label={menu?'Close menu':'Open menu'} onClick={()=>setMenu(!menu)}>{menu?'Close':'Menu'}<span>{menu?'−':'+'}</span></button></div></header>
 <main id="main"><section className="hero wrap"><div className="hero-art"><img src="/protocol-ring.webp" alt="Sculptural titanium ring threaded with mint light" fetchPriority="high" width="1536" height="1024"/></div><div className="hero-copy"><div className="pill"><span className="status-dot"/>BNB SMART CHAIN <span className="pill-divider"/> TESTNET</div><h1>Built on logic.<br/>Open to <em>everyone.</em></h1><p className="hero-description">A connected system for membership, binary rewards and reserve-based token mechanics. Explore the rules. Understand the flow.</p><div className="hero-actions"><External className="button primary" href={APP}>Explore the testnet</External><a className="text-link" href="#protocol"><span className="play">▷</span> How it works</a></div><p className="hero-note">Experimental protocol · Test assets only · Not independently audited</p></div><div className="hero-foot"><span>THE RULES ARE OPEN.<br/><b>THE NEXT STEP IS YOURS.</b></span><a href="#protocol" className="scroll-link">SCROLL TO EXPLORE <span aria-hidden="true">↓</span></a><span className="hero-edition">PROTOCOL OVERVIEW<br/><b>01 / TESTNET EDITION</b></span></div></section>
 <div className="parameter-bar"><div className="wrap parameter-grid"><div><b>02</b><span>Connected core contracts</span></div><div><b>$100</b><span>Per membership unit</span></div><div><b>90%</b><span>Allocated to point rewards</span></div><div><b>3%</b><span>Ordinary buy / sell fee</span></div></div></div>
 <section id="protocol" className="section wrap"><Eyebrow n="01">THE PROTOCOL</Eyebrow><div className="section-heading"><h2>Two contracts.<br/><em>One connected system.</em></h2><p>Membership and token mechanics have distinct roles. Follow each contribution from the moment it enters the system.</p></div><div className="architecture"><article className="architecture-card"><span className="card-index">CONTRACT 01</span><div className="diagram-mini"><Tree left="L" right="R"/></div><h3>The membership layer</h3><p>Register a position, add units and build a two-branch network. Eligible matched points share a funded reward pool.</p><div className="tags"><span>Binary placement</span><span>Point matching</span><span>Hourly payouts</span></div><a href="#binary" className="line-link">Explore the binary plan</a></article><div className="bridge"><span>5%</span><i/><small>UNIT FUNDING</small></div><article className="architecture-card token-card"><span className="card-index">CONTRACT 02</span><div className="formula-display"><span>R</span><hr/><span>S</span><small>SPOT PRICE</small></div><h3>The token layer</h3><p>Buy and redeem with reserve-based pricing. Staged purchases, fees and separate support funds define how tokens move.</p><div className="tags"><span>Curve pricing</span><span>500 USD steps</span><span>Reserve accounting</span></div><a href="#token" className="line-link">Understand FTI mechanics</a></article></div></section>
 <section className="allocation-section"><div className="wrap allocation-grid"><div><Eyebrow n="02">FOLLOW THE FLOW</Eyebrow><h2>Every unit.<br/><em>Fully accounted for.</em></h2><p>See how a membership contribution is allocated. This is a funding breakdown, not an estimate of your earnings.</p><label className="unit-label" htmlFor="units">Membership units <strong>{units}</strong></label><input id="units" type="number" min="1" step="1" value={units} onChange={e=>setUnits(Math.max(1,Math.floor(Number(e.target.value)||1)))}/><div className="range-labels"><span>100 test USD per unit</span><span>No fixed wallet unit ceiling</span></div><div className="contribution">Total contribution <b>${format(units*100)}</b></div></div><div className="allocation-visual"><div className="allocation-top"><span>ALLOCATION MODEL</span><span>100% ASSIGNED</span></div><div className="big-number">90<span>%</span><small>Point reward pool</small></div><div className="allocation-bar" aria-label="90% points, 5% token support, 4% builders, 1% development"><i/><i/><i/><i/></div><div className="allocation-list">{[['Point rewards',90,'mint'],['Token support',5,'white'],['Builder pools',4,'gray'],['Development',1,'dark']].map(([name,pct,color])=><div key={name}><span><i className={color}/>{name}</span><b>${format(units*pct)}</b><small>{pct}%</small></div>)}</div><p className="mini-note">The 5% token allocation funds support pools. It does not mint FTI for the member.</p></div></div></section>
 <section id="binary" className="section wrap binary-section"><Eyebrow n="03">THE BINARY PLAN</Eyebrow><div className="section-heading"><h2>Two branches.<br/><em>Understand the balance.</em></h2><p>Experiment with branch volume and point caps. The smaller branch determines raw matches; the current cap determines paid points.</p></div><div className="binary-grid"><div className="binary-demo"><div className="panel-header"><span>POINT MATCHING LAB</span><span className="subtle-chip">Illustrative</span></div><Tree left={left} right={right}/><div className="input-grid"><label>Left volume<input type="number" min="0" max="1000000" value={left} onChange={e=>setLeft(Math.min(1000000,Math.max(0,+e.target.value||0)))}/></label><label>Right volume<input type="number" min="0" max="1000000" value={right} onChange={e=>setRight(Math.min(1000000,Math.max(0,+e.target.value||0)))}/></label><label>Rank<select value={rank} onChange={e=>setRank(+e.target.value)}>{['Member','Builder I · 100 balanced','Builder II · 200 balanced','Builder III · 500 balanced','Builder IV · 1,000 balanced'].map((s,i)=><option value={i} key={s}>{s}</option>)}</select></label><label>Protection level<select value={level} onChange={e=>setLevel(+e.target.value)}>{[0,1,2,3].map(i=><option key={i} value={i}>Level {i}</option>)}</select></label></div><div className="results" aria-live="polite"><div><span>Paid points</span><b>{paid}</b></div><div><span>Unpaid matches</span><b>{raw-paid}</b></div><div><span>Unbalanced volume</span><b>{Math.abs(left-right)}<small> {left>right?'L':left<right?'R':''}</small></b></div></div><p className="mini-note">Unpaid matched points are retained. This cap illustration excludes attributed funding and is not a payout quote. Protection activates below 16 USD; paid points require 20 USD gross backing.</p></div><div className="binary-steps">{[['01','Start with a position','Registration places a new wallet beneath an existing member, filling the left position before the right.'],['02','Match eligible volume','Purchased units propagate through ancestors. Balanced volume creates raw matches; rank and protection caps apply.'],['03','Allocate funded rewards','Allocation uses eligible points, attributed branch credit and available funding. Rank caps and the 20 USD gross backing requirement bound paid points.'],['04','Receive funded rewards','The keeper settles funded rewards to beneficiaries. Unpaid branch volume remains for later settlement. Optional auto-buy uses 5% of hourly rewards.']].map(([n,title,body])=><article key={n}><span>{n}</span><div><h3>{title}</h3><p>{body}</p></div></article>)}<a href={REVIEW} target="_blank" rel="noopener noreferrer" className="review-link">Read the current rules and limitations</a></div></div></section>
 <section id="token" className="token-section"><div className="wrap"><div className="token-title"><Eyebrow n="04">FTI TOKEN MECHANICS</Eyebrow><h2>Price follows<br/><em>the reserve.</em></h2><p>Purchases add reserves and mint tokens. Redemptions burn tokens and pay from real reserves at the current internal reserve quote.</p></div><div className="token-layout"><div className="curve-panel"><div className="panel-header"><span>FUNDING FLOW</span><div className="segmented" aria-label="Curve direction"><button onClick={()=>setMode('buy')} aria-pressed={mode==='buy'}>Buy</button><button onClick={()=>setMode('sell')} aria-pressed={mode==='sell'}>Sell</button></div></div><div className="curve-text"><b>{mode==='buy'?'Reserve in. Tokens minted.':'Tokens burned. Reserve out.'}</b><span>Illustrative reserve flow · not a price chart or forecast</span></div><CurveChart mode={mode}/><div className="curve-caption"><span>{mode==='buy'?'More reserve enters the pricing curve.':'Payout depends on curve position and fees.'}</span><b>SPOT = R / S</b></div></div><div className="token-facts"><div><span>01 / CURVE</span><h3>Continuous pricing</h3><p>Price changes with reserve and supply. With nonzero supply, price equals pricing reserve divided by supply. Support is accounted separately.</p></div><div><span>02 / ACCESS</span><h3>Defined trading rules</h3><p>Buying uses 500 USD steps and wallet allowances. Larger ordinary sales have reserve and hourly limits. Transfers burn 3%.</p></div><div><span>03 / SUPPORT</span><h3>Funded, finite support</h3><p>Support uses available funds. It cannot guarantee a minimum price, recovery or return of purchase cost.</p></div></div></div></div></section>
 <section className="section wrap journey"><Eyebrow n="05">EXPLORE WITH TEST ASSETS</Eyebrow><div className="section-heading"><h2>From understanding<br/><em>to your first test.</em></h2><External href={APP} className="button outline">Open testnet application</External></div><div className="journey-grid">{[['01','Connect','Use a test wallet on BNB Smart Chain testnet, chain ID 97. Keep real funds separate.'],['02','Register','Choose a registered sponsor and use test USD to purchase membership units. Repeat purchases increase the same wallet position.'],['03','Explore','Inspect the network, balances and allocation process. Try a token purchase.'],['04','Review','Check allowances and transaction receipts. Sell eligible tokens and verify your resulting balance.']].map(([n,t,p])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{p}</p></article>)}</div><p className="app-note">The test application opens separately. Its availability depends on the testnet and its RPC service.</p></section>
 <section id="development" className="development-section"><div className="wrap"><Eyebrow n="06">OPEN DEVELOPMENT</Eyebrow><div className="section-heading"><h2>See what works.<br/><em>Know what comes next.</em></h2><p>Development status should be as visible as the product. Explore the current rules, governance and the checks that still need to be completed.</p></div><div className="development-grid"><article><span className="stage-label">AVAILABLE FOR TESTING</span><h3>The current testnet</h3><ul><li>Binary placement and unit purchases</li><li>Funded point allocation and hourly payouts</li><li>Staged token purchases and redemptions</li><li>Public contract source and tests</li></ul><External href={REPO} className="line-link">Read the whitepaper</External></article><article><span className="stage-label candidate">CONTINUITY MODEL</span><h3>Continuity and governance</h3><ul><li>Proxy-based contract upgrades</li><li>Council and delayed governance</li><li>Recovery freeze and migration checks</li><li>Upgrade validation remains essential</li></ul><External href={sites.council} className="line-link">Open council panel</External></article><article className="review-card"><span className="stage-label review">REVIEW IN PROGRESS</span><h3>Questions we must resolve</h3><ul><li>Attributed reward funding</li><li>Purchase and sale limits</li><li>Settlement capacity at larger scale</li><li>Independent security audit</li></ul><External href={sites.roadmap} className="line-link">View the roadmap</External></article></div><div className="contract-row"><div><small>CURRENT TESTNET TOKEN · CHAIN 97</small><code>{token||"Live contract address unavailable"}</code></div><div><button className="button small outline" disabled={!token} onClick={copy} aria-live="polite">{copied?'Copied':'Copy address'}</button>{token&&<External className="button small outline" href={"https://testnet.bscscan.com/address/"+token}>Explorer</External>}</div></div></div></section>
 <section id="faq" className="section wrap faq-section"><div><Eyebrow n="07">A FEW IMPORTANT ANSWERS</Eyebrow><h2>Clarity<br/><em>comes first.</em></h2><p>Understand the rules and limitations before you connect a wallet.</p><External href={REPO} className="text-link">Read the whitepaper</External></div><div className="faqs">{faq.map(([q,a],i)=><article key={q} className={opened===i?'expanded':''}><h3><button id={'question-'+i} aria-expanded={opened===i} aria-controls={'answer-'+i} onClick={()=>setOpened(opened===i?-1:i)}>{q}<span aria-hidden="true">{opened===i?'−':'+'}</span></button></h3><div id={'answer-'+i} role="region" aria-labelledby={'question-'+i} hidden={opened!==i}><p>{a}</p></div></article>)}</div></section>
 <section className="closing wrap"><div className="closing-top"><Mark/><span>UNDERSTAND. EXPLORE. VERIFY.</span></div><h2>The next step starts<br/>with <em>understanding.</em></h2><div className="closing-actions"><External className="button primary" href={APP}>Explore FTI testnet</External><External className="button outline" href={REPO}>Read the whitepaper</External></div><p>Test assets only. No guaranteed income, token price or principal repayment.</p></section></main>
 <footer className="wrap"><div className="footer-top"><a href="#" className="logo"><Mark/>FTI Protocol</a><p>An open look at the rules<br/>behind the system.</p><div><a href="#protocol">Protocol</a><a href="#binary">Binary plan</a><External href={sites.token}>Token site</External></div><div><a href="#development">Development</a><External href={sites.roadmap}>Roadmap</External><External href={REPO}>Whitepaper</External></div></div><div className="footer-word">FTI PROTOCOL<span>©</span></div><div className="footer-bottom"><span>© {new Date().getFullYear()} FTI Protocol</span><span>BNB SMART CHAIN TESTNET</span><span>ENGLISH / EN</span></div></footer></div>
}


