import React,{useState,useEffect} from 'react';
import {createRoot} from 'react-dom/client';
import {t,language,initializeLanguage} from '../../frontend/locale.js';
import {RANKS,CAPS} from './protocol-data.mjs';
import './style.css';
initializeLanguage();
const REPO='https://github.com/Rezamoradifar/fti-protocol',APP=__FTI_APP_URL__||'/app/';
const base=new URL(APP,location.origin),TOKEN=new URL('/token/',base).href,ADMIN=new URL('/admin/',base).href;
const fmt=v=>v===undefined?'—':(Number(v)/1e18).toLocaleString('en-US',{maximumFractionDigits:6});
function Link({href,children,className=''}){return <a href={href} className={className} {...(/github.com|bscscan.com/.test(href)?{target:'_blank',rel:'noreferrer'}:{})}>{children}</a>}
function Section({id,n,title,copy,children}){return <section id={id} className="section wrap"><div className="section-heading"><div><span className="kicker">{n} / FTI PROTOCOL</span><h2>{title}</h2></div><p>{copy}</p></div>{children}</section>}
function App(){
 const[cfg,setCfg]=useState(null),[state,setState]=useState(null),[error,setError]=useState(false),[rank,setRank]=useState(0),[level,setLevel]=useState(0),[left,setLeft]=useState(30),[right,setRight]=useState(24),[open,setOpen]=useState(-1),[menu,setMenu]=useState(false);
 useEffect(()=>{const abort=new AbortController();async function refresh(){try{const[c,s]=await Promise.all(['/api/config','/api/state'].map(async p=>{const r=await fetch(new URL(p,base),{signal:abort.signal,cache:'no-store'});if(!r.ok)throw Error('API unavailable');return r.json();}));if(c.tokenContract!=='FTIReserveTokenV3'||c.binaryContract!=='FundedBinaryPlan')throw Error('V3 required');setCfg(c);setState(s);setError(false);}catch(e){if(e.name!=='AbortError')setError(true);}}refresh();const timer=setInterval(refresh,30000);return()=>{abort.abort();clearInterval(timer);};},[]);
 const matched=Math.min(left,right),paid=Math.min(matched,CAPS[level][rank]);
 const spaces=[[APP,t('Your membership','عضویت شما'),t('Register, add units, inspect both branches and receive finalized rewards.','ثبت عضویت، افزودن واحد، مشاهده شاخه‌ها و دریافت پاداش نهایی‌شده.')],[TOKEN,t('Your FTI tokens','توکن‌های FTI شما'),t('Buy, sell and transfer with live quotes, explicit minimum output and visible fees.','خرید، فروش و انتقال با نرخ زنده، حداقل دریافتی مشخص و کارمزد شفاف.')],[ADMIN,t('Protocol operations','عملیات پروتکل'),t('Follow settlement queues, council proposals and timelock execution.','پیگیری صف تسویه، پیشنهادهای شورا و اجرای عملیات پس از قفل زمانی.')]];
 const faqs=[
 [t('What do I need to begin?','برای شروع چه نیاز دارم؟'),t('A BNB Testnet wallet, test BNB for gas, test USD from the faucet and a sponsor with an available position.','ولت روی BNB Testnet، مقداری BNB آزمایشی برای کارمزد، دلار آزمایشی از پنل و معرف دارای جای خالی.')],
 [t('Can I buy more units in one position?','می‌توانم در همان جایگاه دوباره واحد بخرم؟'),t('Yes. Add units to the existing position without changing your sponsor or placement.','بله؛ به همان جایگاه واحد اضافه می‌شود و معرف و محل جایگاه تغییر نمی‌کند.')],
 [t('Are tokens locked?','توکن‌ها قفل دارند؟'),t('V3 has no time or wallet-count locks. Pause, emergency, purchase allowances and sale caps still apply.','V3 قفل زمانی یا شرط تعداد ولت ندارد. توقف، حالت اضطراری، سقف خرید و محدودیت فروش همچنان اعمال می‌شوند.')],
 [t('Where does auto-buy funding come from?','وجه خرید خودکار از کجا می‌آید؟'),t('5% of the eligible hourly reward of the ranked Builder who enables it. It is not taken from monthly Builder rewards. Failed purchases preserve the funds for retry.','۵٪ پاداش ساعتی واجد شرایط همان بیلدر که اتوبای را فعال کرده است؛ این وجه از پاداش ماهانه بیلدر نیست. وجه خرید ناموفق برای تلاش مجدد حفظ می‌شود.')],
 [t('Is $20 a guaranteed point reward?','آیا پاداش هر پوینت ۲۰ دلار تضمین شده است؟'),t('$20 is a protection target. Rewards depend on funded branch credits and hourly caps. Protection adjusts when the funding falls below the target.','۲۰ دلار هدف سیستم حفاظت است. پاداش به اعتبار تأمین‌شده شاخه‌ها و سقف پوینت ساعتی بستگی دارد؛ زیر هدف، سطح حفاظت تنظیم می‌شود.')],
 [t('What happens on the last-holder exit?','در خروج آخرین دارنده چه می‌شود؟'),t('Full-supply sales bypass ordinary caps. The seller receives the net payout; the final fee and remaining support go to development. The next opening quote is $0.20.','فروش کل عرضه از سقف‌های عادی معاف است. مبلغ خالص به فروشنده پرداخت می‌شود؛ کارمزد نهایی و مانده حمایت به توسعه می‌روند. نرخ آغاز چرخه بعدی ۰٫۲۰ دلار است.')]];
 return <><header className="site-header"><div className="wrap header-inner"><a href="#" className="brand"><img src="/app/favicon.svg" alt="" width="32" height="32"/><span>FTI <small>PROTOCOL</small></span></a><button className="menu-button" aria-expanded={menu} aria-controls="site-nav" onClick={()=>setMenu(!menu)}>{t('Menu','منو')}</button><nav id="site-nav" className={menu?'open':''} aria-label={t('Main navigation','ناوبری اصلی')}>{[['#protocol','Protocol','پروتکل'],['#binary','Binary plan','پلن باینری'],['#token','Token','توکن'],['#resources','Contracts','قراردادها']].map(([href,en,fa])=><a key={href} href={href} onClick={()=>setMenu(false)}>{t(en,fa)}</a>)}</nav><div className="header-actions"><button className="language" aria-label={t('Change language','تغییر زبان')} onClick={()=>{localStorage.setItem('fti-language',language==='fa'?'en':'fa');location.reload();}}>{language==='fa'?'EN':'FA'}</button><Link href={APP} className="button compact">{t('Open dashboard','ورود به پنل')}</Link></div></div></header><main>
 <section className="hero wrap"><div className="hero-copy"><span className="pill">{cfg?.chainId===31337?t('LOCAL PREVIEW','پیش‌نمایش محلی'):'BNB TESTNET · 97'}</span><h1>{t('One protocol.','یک پروتکل.')}<br/><em>{t('Everything connected.','همه چیز یکپارچه.')}</em></h1><p>{t('Membership, funded rewards and reserve-based tokens. Explore the rules, inspect the contracts and manage everything from your wallet.','عضویت، پاداش‌های تأمین‌شده و توکن مبتنی بر ذخیره. قوانین را بشناسید، قراردادها را بررسی کنید و همه چیز را از ولت خود مدیریت کنید.')}</p><div className="actions"><Link href={APP} className="button">{t('Start with your wallet','شروع از پنل اعضا')}</Link><Link href={TOKEN} className="button outline">{t('Explore FTI token','مشاهده توکن FTI')}</Link></div><span className="hero-note">{t('Test assets only · no real USD value','فقط دارایی آزمایشی · بدون ارزش دلار واقعی')}</span></div><div className="hero-visual"><img src="/protocol-ring.webp" alt={t('FTI protocol illustration','تصویر پروتکل FTI')} fetchPriority="high"/><div className="visual-caption"><span>FTI RESERVE TOKEN</span><b>R / S</b><small>{t('Reserve ÷ supply','ذخیره ÷ عرضه')}</small></div></div></section>
 <section className="wrap live-section" aria-label={t('Live protocol snapshot','نمای زنده پروتکل')}><div className="live-caption"><span>{t('Read from the configured contracts','خوانده‌شده از قراردادهای فعال')}</span><small role="status">{error?t('Live data unavailable. Check the connection in the dashboard.','اطلاعات زنده در دسترس نیست؛ اتصال را در پنل بررسی کنید.'):state?t('Live contract data','اطلاعات زنده قرارداد'):t('Connecting to contracts…','در حال اتصال به قراردادها…')}</small></div><div className="live-grid">{[[t('Internal FTI price','قیمت داخلی FTI'),fmt(state?.price),t('Test USD / FTI','دلار آزمایشی / FTI')],[t('Pricing reserve','ذخیره قیمت‌گذاری'),fmt(state?.reserve),t('Test USD','دلار آزمایشی')],[t('Membership positions','جایگاه‌های عضویت'),state?.count||'—',t('Registered on-chain','ثبت‌شده روی شبکه')],[t('Current cycle','چرخه فعلی'),state?.cycle||'—',t('First $0.10 · restarts $0.20','آغاز ۰٫۱۰ · چرخه بعد ۰٫۲۰ دلار')]].map(([title,value,detail])=><article key={title}><span>{title}</span><strong>{value}</strong><small>{detail}</small></article>)}</div></section>
 <Section id="protocol" n="01" title={t('A clear path for every action.','برای هر کار، یک مسیر روشن.')} copy={t('The member panel, token workspace and governance tools share one deployment. Your wallet approves every transaction.','پنل اعضا، فضای توکن و ابزارهای شورا از یک مجموعه قرارداد استفاده می‌کنند. هر تراکنش با تأیید ولت شما انجام می‌شود.')}><div className="space-grid">{spaces.map(([href,title,copy],i)=><article key={href} className="space-card"><span className="card-number">0{i+1}</span><h3>{title}</h3><p>{copy}</p><Link href={href} className="text-link">{t('Open workspace','ورود به این بخش')} ↗</Link></article>)}</div></Section>
 <Section id="binary" n="02" title={t('Your position. Your branches.','جایگاه شما، شاخه‌های شما.')} copy={t('Each unit costs 100 test USD. Repeat purchases add units to the same position. New members fill left first, then right.','هر واحد عضویت ۱۰۰ دلار آزمایشی است. خرید مجدد به همان جایگاه واحد اضافه می‌کند. چیدمان عضو جدید ابتدا چپ و سپس راست است.')}><div className="binary-grid"><article className="allocation-card"><span className="pill">100 TEST USD / UNIT</span><h3>{t('Every contribution has a destination.','سهم هر صندوق مشخص است.')}</h3><div className="allocation-list">{[['90%',t('Binary point pool','صندوق پوینت باینری')],['5%',t('Token price support','صندوق حمایت قیمت توکن')],['4%',t('Monthly Builder pool','صندوق پاداش ماهانه بیلدر')],['1%',t('Development','توسعه')]].map(([n,label])=><div key={n}><strong>{n}</strong><span>{label}</span></div>)}</div><p>{t('Charity allocation is removed from this V3 model.','سهم خیریه از این مدل V3 حذف شده است.')}</p></article><article className="calculator"><span className="kicker">{t('ILLUSTRATIVE POINT MATCHING','مثال محاسبه پوینت')}</span><h3>{t('Explore hourly point caps.','سقف پوینت ساعتی را بررسی کنید.')}</h3><div className="field-grid"><label>{t('Rank','رنک')}<select value={rank} onChange={e=>setRank(Number(e.target.value))}>{RANKS.map((r,i)=><option key={r.name} value={i}>{i===0?t('Member','عضو'):t('Builder','بیلدر')+' '+i}</option>)}</select></label><label>{t('Protection level','سطح حفاظت')}<select value={level} onChange={e=>setLevel(Number(e.target.value))}>{[0,1,2,3].map(n=><option key={n}>{n}</option>)}</select></label>{[[left,setLeft,t('Eligible left points','پوینت واجد شرایط چپ')],[right,setRight,t('Eligible right points','پوینت واجد شرایط راست')]].map(([value,set,label])=><label key={label}>{label}<input type="number" min="0" max="1000000" step="1" value={value} onChange={e=>set(Math.max(0,Math.min(1000000,Math.floor(Number(e.target.value)||0))))}/></label>)}</div><div className="calculator-result" aria-live="polite">{[[t('Matched','متوازن'),matched],[t('Within cap','در سقف ساعتی'),paid],[t('Flushed','فلش‌شده'),matched-paid]].map(([label,n])=><div key={label}><span>{label}</span><b>{n}</b></div>)}</div><p>{t('This example counts points, not cash income. Actual rewards use funded branch credits. $20 is the point-value protection target.','این مثال تعداد پوینت را نشان می‌دهد، نه درآمد نقدی. پاداش واقعی از اعتبار تأمین‌شده شاخه‌ها محاسبه می‌شود. ۲۰ دلار هدف حفاظت ارزش پوینت است.')}</p></article></div></Section>
 <Section id="ranks" n="03" title={t('Know your limits before you buy.','سقف خرید را پیش از معامله ببینید.')} copy={t('Builder limits double at each 10× price milestone, up to 16×. Member rank stays at the base limit. The contract reports your actual remaining allowance.','سقف خرید بیلدر با هر جهش ده‌برابری قیمت، دو برابر می‌شود تا ضریب ۱۶×. رنک عضو ضریب پایه دارد. سقف باقیمانده واقعی را قرارداد اعلام می‌کند.')}><div className="table-wrap"><table><thead><tr>{[t('Rank','رنک'),t('Balanced lifetime points','پوینت متوازن کل'),t('Base buy limit / unit','سقف پایه خرید / واحد'),t('Hourly point cap · level 0','سقف پوینت ساعتی · سطح ۰')].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{RANKS.map((r,i)=><tr key={r.name}><td>{i===0?t('Member','عضو'):t('Builder','بیلدر')+' '+i}</td><td>{r.threshold}</td><td>{r.buyLimit} USD</td><td>{CAPS[0][i]}</td></tr>)}</tbody></table></div></Section>
 <section id="token" className="section token-section"><div className="wrap"><div className="section-heading"><div><span className="kicker">04 / FTI TOKEN</span><h2>{t('Visible reserve. Clear mechanics.','ذخیره قابل مشاهده، قوانین روشن.')}</h2></div><p>{t('Internal price is pricing reserve divided by token supply. No premint, virtual supply or time locks.','قیمت داخلی برابر ذخیره قیمت‌گذاری تقسیم بر عرضه توکن است. پیش‌صدور، عرضه مجازی و قفل زمانی وجود ندارد.')}</p></div><div className="token-rules" id="token-rules">{[[t('Trading fee','کارمزد خرید و فروش'),'3%',t('Ordinary trade fees stay in reserve. The final exit fee goes to development.','کارمزد معاملات عادی در ذخیره قیمت‌گذاری می‌ماند. کارمزد خروج نهایی به توسعه پرداخت می‌شود.')],[t('Transfer burn','سوزاندن انتقال'),'3%',t('The recipient gets 97% of your debit; 3% is burned, rounded up.','کل مقدار از ولت کسر می‌شود؛ گیرنده ۹۷٪ می‌گیرد و ۳٪ با گردکردن رو به بالا سوزانده می‌شود.')],[t('Small-sale exemption','معافیت فروش کوچک'),'≤ $500',t('Gross sales up to $500 bypass ordinary caps. Minimum output and deadline always apply.','فروش با مبلغ ناخالص حداکثر ۵۰۰ دلار از سقف‌های عادی مستثناست. حداقل دریافتی و مهلت همیشه اعمال می‌شوند.')],[t('Larger ordinary sales','فروش عادی بزرگ‌تر'),'5% / 20%',t('5% current reserve per sale; 20% net hourly outflow against opening reserve. Final full-supply exits are exempt.','سقف هر فروش ۵٪ ذخیره جاری و خروج خالص ساعتی ۲۰٪ ذخیره آغاز بازه است. خروج نهایی کل عرضه معاف است.')]].map(([title,n,copy])=><article key={title}><span>{title}</span><strong>{n}</strong><p>{copy}</p></article>)}</div><div className="support-note"><div><h3>{t('Support stays separate until needed.','حمایت تا زمان نیاز، جدا می‌ماند.')}</h3><p>{t('A drop below the recorded high triggers the minimum available reserve injection toward the high plus one price unit. Support can be depleted; this adds no new sale veto. The next normal cycle opens at $0.20.','افت زیر بالاترین قیمت ثبت‌شده، حداقل تزریق قابل تأمین را برای رسیدن به سقف قبلی به‌علاوه یک واحد قیمت فعال می‌کند. اتمام حمایت مانع فروش تازه‌ای ایجاد نمی‌کند. نرخ آغاز چرخه عادی بعدی ۰٫۲۰ دلار است.')}</p></div><Link href={TOKEN} className="button outline">{t('View live reserves','مشاهده ذخیره زنده')}</Link></div></div></section>
 <Section id="settlement" n="05" title={t('From allocation to your wallet.','از محاسبه پاداش تا ولت شما.')} copy={t('Hourly settlement, cash payments and auto-buy follow separate on-chain steps. Pending balances remain visible in your dashboard.','تسویه ساعتی، پرداخت نقدی و خرید خودکار مراحل جداگانه روی شبکه دارند. موجودی‌های در انتظار در پنل قابل مشاهده‌اند.')}><div className="space-grid">{[['100',t('Batched reward payments','پرداخت دسته‌ای پاداش'),t('Each Reward transaction pays up to 100 finalized beneficiaries. Keeper continues the remaining queue.','هر تراکنش Reward تا ۱۰۰ ولت ذی‌نفع را پرداخت می‌کند؛ Keeper صف باقیمانده را ادامه می‌دهد.'),APP+'#rewards'],['5%',t('Hourly auto-buy','خرید خودکار از پاداش ساعتی'),t('Ranked Builders can reserve 5% of eligible hourly rewards for ordinary token purchases. Failed buys preserve funds for retry.','بیلدر می‌تواند ۵٪ پاداش ساعتی واجد شرایط خود را برای خرید عادی توکن کنار بگذارد. وجه خرید ناموفق برای تلاش مجدد حفظ می‌شود.'),APP+'#rewards'],['5 / 7',t('Council and 72-hour timelock','شورا و قفل زمانی ۷۲ ساعته'),t('Five guardians authorize proposals. Ordinary operations use the timelock; emergency unwind enables permanent proportional redemption.','پنج رأی از هفت نگهبان برای پیشنهادها لازم است. عملیات عادی قفل زمانی دارند؛ خروج اضطراری بازپرداخت نسبی دائمی را فعال می‌کند.'),ADMIN]].map(([n,title,copy,href])=><article key={n} className="space-card"><span className="card-number">{n}</span><h3>{title}</h3><p>{copy}</p><Link href={href} className="text-link">{t('Open workspace','ورود به این بخش')} ↗</Link></article>)}</div></Section>
 <Section id="resources" n="06" title={t('The active contracts, in one place.','قراردادهای فعال، در یک نگاه.')} copy={t('Addresses come from this service’s deployment configuration. Explorer links are shown only for BNB Testnet.','آدرس‌ها از تنظیمات استقرار همین سرویس خوانده می‌شوند. لینک اکسپلورر فقط برای BNB Testnet نمایش داده می‌شود.')}><div className="contracts">{Object.entries({usd:'MockUSD',token:'FTIReserveTokenV3',binary:'FundedBinaryPlan',council:'SevenGuardianCouncil',timelock:'FTITimelock'}).map(([key,name])=><article key={key}><div><b>{name}</b><span>{cfg?.[key]||t('Waiting for configuration…','در انتظار تنظیمات استقرار…')}</span></div>{cfg?.chainId===97&&cfg[key]&&<Link href={'https://testnet.bscscan.com/address/'+cfg[key]+'#code'} className="text-link">{t('Explorer','اکسپلورر')} ↗</Link>}</article>)}</div><div className="source-row"><span>{cfg?.sourceRevision?t('Source revision','نسخه کد')+': '+cfg.sourceRevision.slice(0,12):t('V3 contract source','کد قراردادهای V3')}</span><Link href={REPO+'/tree/'+(cfg?.sourceRevision||'main')} className="text-link">{t('Inspect source on GitHub','مشاهده کد در GitHub')} ↗</Link></div></Section>
 <section id="faq" className="section wrap faq-section"><div><span className="kicker">07 / FTI PROTOCOL</span><h2>{t('Understand before you transact.','قبل از تراکنش، قوانین را بشناسید.')}</h2><p>{t('The essentials, right here.','پاسخ‌های اصلی، همین‌جا در دسترس شماست.')}</p></div><div className="faqs">{faqs.map(([q,a],i)=><article key={i}><h3><button aria-expanded={open===i} aria-controls={'faq-'+i} onClick={()=>setOpen(open===i?-1:i)}>{q}<span aria-hidden="true">{open===i?'−':'+'}</span></button></h3><div id={'faq-'+i} hidden={open!==i}><p>{a}</p></div></article>)}</div></section>
 <section className="closing wrap"><span className="kicker">FTI PROTOCOL</span><h2>{t('Your next step starts here.','قدم بعدی از همین‌جا شروع می‌شود.')}</h2><div className="actions"><Link href={APP} className="button">{t('Open your dashboard','ورود به پنل شما')}</Link><Link href={TOKEN} className="button outline">{t('View the token','مشاهده توکن')}</Link></div><p>{t('Test assets only. No guaranteed income, token price or principal repayment.','فقط دارایی آزمایشی. درآمد، قیمت توکن و بازپرداخت سرمایه تضمین نمی‌شود.')}</p></section></main><footer className="wrap"><a href="#" className="brand">FTI <small>PROTOCOL</small></a><nav>{[[APP,t('Member dashboard','پنل اعضا')],[TOKEN,t('FTI token','توکن FTI')],[ADMIN,t('Governance','شورا و مدیریت')],[REPO,'GitHub']].map(([href,label])=><Link key={href} href={href}>{label}</Link>)}</nav><small>© {new Date().getFullYear()} FTI Protocol · {cfg?.chainId===31337?'LOCAL':'BNB TESTNET'}</small></footer></>;
}
createRoot(document.getElementById('root')).render(<App/>);
