import React,{useState,useEffect} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';
import {RankExplorer,Settlement,TokenRules,Guide,Resources} from './sections.jsx';
import {CAPS} from './protocol-data.mjs';
const REPO='https://github.com/Rezamoradifar/fti-protocol';
const APP=__FTI_APP_URL__||'https://ftiprotocol.com/app/';
const TOKEN=APP.startsWith('/')?'/token/':new URL('/token/',APP).href;
const ADMIN=APP.startsWith('/')?'/admin/':new URL('/admin/',APP).href;
const REVIEW=REPO+'/blob/fix/liquidity-safety/docs/ECONOMIC-REVIEW.md';
const format=n=>new Intl.NumberFormat('en-US',{maximumFractionDigits:0}).format(n);
function Mark(){return <span className="brand-mark" aria-hidden="true"><i/><i/><i/></span>}
function External({href,children,className=''}){return <a className={className} href={href} target={href===APP?undefined:'_blank'} rel={href===APP?undefined:'noopener noreferrer'}>{children}</a>}
function Eyebrow({n,children}){return <div className="eyebrow"><span>{n}</span>{children}</div>}
function Tree({left,right}){return <svg className="tree" viewBox="0 0 520 290" role="img" aria-label={`A binary position with ${left} left units and ${right} right units`}><g fill="none" stroke="#3c5548" strokeWidth="1.5"><path d="M260 62V102H130V144M260 102H390V144M130 184V217H65V242M130 217H195V242M390 184V217H325V242M390 217H455V242"/></g><g fill="#15241c" stroke="#526f5c"><rect x="229" y="10" width="62" height="60" rx="16"/><rect x="99" y="134" width="62" height="58" rx="14"/><rect x="359" y="134" width="62" height="58" rx="14"/></g><g fill="#b2ffd0"><circle cx="260" cy="33" r="7"/><path d="M246 54c0-15 28-15 28 0z"/><circle cx="130" cy="158" r="7"/><path d="M116 179c0-15 28-15 28 0z"/><circle cx="390" cy="158" r="7"/><path d="M376 179c0-15 28-15 28 0z"/></g>{[65,195,325,455].map(x=><g key={x}><circle cx={x} cy="255" r="15" fill="#15241c" stroke="#526f5c"/><circle cx={x} cy="255" r="4" fill="#91b49d"/></g>)}<g fill="#dae9df" fontSize="14" fontFamily="Arial"><text x="130" y="120" textAnchor="middle">LEFT · {left}</text><text x="390" y="120" textAnchor="middle">RIGHT · {right}</text></g></svg>}
function CurveChart({mode}){const buy=mode==='buy';return <svg viewBox="0 0 610 250" className="curve-chart" role="img" aria-label={buy?'Illustrative rising purchase curve, not a price forecast':'Illustrative declining redemption curve, not a price forecast'}><defs><linearGradient id="chartFill" x1="0" y1="0" x2="0" y2="1"><stop stopColor="#b2ffd0" stopOpacity=".25"/><stop offset="1" stopColor="#b2ffd0" stopOpacity="0"/></linearGradient></defs>{[45,95,145,195].map(y=><path key={y} d={`M20 ${y}H590`} stroke="#243c2e" strokeDasharray="3 6"/>)}<path d={buy?'M20 213 C200 205 390 180 590 28 V225H20Z':'M20 28 C180 150 360 206 590 213 V225H20Z'} fill="url(#chartFill)"/><path d={buy?'M20 213 C200 205 390 180 590 28':'M20 28 C180 150 360 206 590 213'} stroke="#b2ffd0" strokeWidth="3" fill="none"/><circle cx="590" cy={buy?28:213} r="5" fill="#b2ffd0"/><text x="20" y="245" fill="#99ada2" fontSize="12">START</text><text x="590" y="245" textAnchor="end" fill="#99ada2" fontSize="12">{buy?'MORE TOKENS MINTED':'MORE TOKENS REDEEMED'}</text></svg>}
const faq=[
 ['What is FTI Protocol?','FTI is an experimental membership and token system. The V2 candidate keeps binary rewards and token accounting separate: the token starts with zero supply, uses real reserve/share accounting, has no time or wallet-count vesting locks, and adds transparent sell protection.'],
 ['Does membership guarantee income?','No. Membership units are not a promise of principal repayment or income. Rewards depend on eligible points and available funding. The current contracts distribute participant-funded pools; they do not generate an external investment yield.'],
 ['How does the binary plan match volume?','Each position has a left and right branch. Raw matched points are the smaller of the two available volumes. Rank and protection level cap the points paid in an epoch. Matched points above that cap are consumed; only the unbalanced side carries forward.'],
 ['Why can a token sale be unavailable?','In V2 there is no 30/90-day or wallet-count token lock. A sale can fail because the user minimum output is not met, the normal 5% single-sale cap or 15% hourly reserve-capacity limit is reached, collateral is unavailable, or the transaction cannot complete. A 5-of-7 emergency can switch the protocol to redemption-only mode.'],
 ['Is the protocol independently audited?','No. Source code and diagnostic tests are available, but independent auditing is not complete. Economic review identified carried-pool capture and transaction-splitting concerns. These findings are documented and remain part of the redesign work.'],
 ['Are scheduled exits available in the current deployment?','Scheduled exits and 5% support-window budgets belong to a separate experimental candidate. They are not active in the existing public testnet deployment. This landing page explains both versions and does not move funds.'],
 ['How do ranks and protection levels interact?','Rank thresholds are 100, 200, 500 and 1,000 on the weaker cumulative lifetime branch. Protection levels change the point cap, not a guaranteed USD payout. Explore the rank table above. Rank promotion is applied after that epoch’s points are capped.'],
 ['Is the builder reward paid every month forever?','No. Pools are processed monthly, but each address can claim each qualifying rank pool only once. A payout is limited to the smaller of an equal eligible share and 20% of the pool. Unused funds carry forward.'],
 ['Does the $20 threshold guarantee a point value?','No. The threshold controls protection-level changes for later settlements. Actual point value is the funded pool divided by eligible paid points and can differ substantially from $20.'],
 ['Who processes the hourly settlement?','Settlement is permissionless: a keeper or another caller submits transactions to process volume, match members and allocate rewards. Without those transactions, reaching the hourly boundary alone does not distribute rewards.'],
 ['Can I use real money here?','This release is for test assets only. Use BNB testnet and test tokens. MockUSD is not a real stablecoin, and an FTI testnet balance has no promised monetary value.']
];
function App(){
 const [menu,setMenu]=useState(false),[units,setUnits]=useState(1),[left,setLeft]=useState(30),[right,setRight]=useState(12),[rank,setRank]=useState(1),[level,setLevel]=useState(0),[mode,setMode]=useState('buy'),[opened,setOpened]=useState(0),[copied,setCopied]=useState(false),[faqSearch,setFaqSearch]=useState('');
 const caps=CAPS;
 const raw=Math.min(left,right),paid=Math.min(raw,caps[level][rank]);
 useEffect(()=>{function escape(e){if(e.key==='Escape')setMenu(false)}document.addEventListener('keydown',escape);return()=>document.removeEventListener('keydown',escape)},[]);
 async function copy(){try{await navigator.clipboard.writeText('0x127bEEe5c89fDf42Bb056BBD5D4491982880eE91');setCopied(true);setTimeout(()=>setCopied(false),2200)}catch{setCopied(false)}}
 return <><a className="skip" href="#main">Skip to content</a><header><div className="nav wrap"><a className="logo" href="#"><Mark/><span>FTI<span className="logo-light"> Protocol</span></span></a><nav className={menu?'open':''} aria-label="Main navigation">{[['Protocol','protocol'],['Binary plan','binary'],['Token','token'],['Development','development']].map(([label,id])=><a key={id} href={'#'+id} onClick={()=>setMenu(false)}>{label}</a>)}<a href={TOKEN} onClick={()=>setMenu(false)}>FTI token ↗</a></nav><External href={APP} className="button small nav-cta">Member dashboard</External><button className="menu" aria-expanded={menu} aria-label={menu?'Close menu':'Open menu'} onClick={()=>setMenu(!menu)}>{menu?'Close':'Menu'}<span>{menu?'−':'+'}</span></button></div></header>
 <main id="main"><section className="hero wrap"><div className="hero-art"><img src="/protocol-ring.webp" alt="Sculptural titanium ring threaded with mint light" fetchPriority="high" width="1536" height="1024"/></div><div className="hero-copy"><div className="pill"><span className="status-dot"/>BNB SMART CHAIN <span className="pill-divider"/> TESTNET</div><h1>Built on logic.<br/>Open to <em>everyone.</em></h1><p className="hero-description">A connected system for membership, binary rewards and reserve-based token mechanics. Explore the rules. Understand the flow.</p><div className="hero-actions"><External className="button primary" href={APP}>Open member dashboard</External><a className="text-link" href="#protocol"><span className="play">▷</span> How it works</a></div><p className="hero-note">Experimental protocol · Test assets only · Not independently audited</p></div><div className="hero-foot"><span>THE RULES ARE OPEN.<br/><b>THE NEXT STEP IS YOURS.</b></span><a href="#protocol" className="scroll-link">SCROLL TO EXPLORE</a><span className="hero-edition">PROTOCOL OVERVIEW<br/><b>01 / TESTNET EDITION</b></span></div></section>
 <div className="parameter-bar"><div className="wrap parameter-grid"><div><b>02</b><span>Connected core contracts</span></div><div><b>$100</b><span>Per membership unit</span></div><div><b>90%</b><span>Allocated to point rewards</span></div><div><b>0</b><span>Pre-minted V2 token supply</span></div></div></div>
 <div className="section-directory wrap" aria-label="Explore the page"><span>INSIDE THE PROTOCOL</span><a href="#binary">Point matching</a><a href="#ranks">Rank explorer</a><a href="#token-rules">Fees & protection</a><a href="#get-started">Testnet guide</a><a href="#resources">Contract directory</a></div><section id="protocol" className="section wrap"><Eyebrow n="01">THE PROTOCOL</Eyebrow><div className="section-heading"><h2>Two contracts.<br/><em>One connected system.</em></h2><p>Membership and token mechanics have distinct roles. Follow each contribution from the moment it enters the system.</p></div><div className="architecture"><article className="architecture-card"><span className="card-index">CONTRACT 01</span><div className="diagram-mini"><Tree left="L" right="R"/></div><h3>The membership layer</h3><p>Register a position, add units and build a two-branch network. Eligible matched points share a funded reward pool.</p><div className="tags"><span>Binary placement</span><span>Point matching</span><span>Pull payments</span></div><a href="#binary" className="line-link">Explore the binary plan</a></article><div className="bridge"><span>5%</span><i/><small>UNIT FUNDING</small></div><article className="architecture-card token-card"><span className="card-index">CONTRACT 02</span><div className="formula-display"><span>R</span><hr/><span>S</span><small>INTERNAL RESERVE / SHARE</small></div><h3>The token layer</h3><p>Buy and redeem against real recorded reserves. V2 removes vesting locks, allocates one percentage point of the 3% trade fee to animal-support FTI and uses slippage plus anti-whale sell controls.</p><div className="tags"><span>Zero-start supply</span><span>No vesting locks</span><span>Reserve accounting</span></div><a href={TOKEN} className="line-link">Open the FTI token site</a></article></div></section>
 <section className="allocation-section"><div className="wrap allocation-grid"><div><Eyebrow n="02">FOLLOW THE FLOW</Eyebrow><h2>Every unit.<br/><em>Fully accounted for.</em></h2><p>See how a membership contribution is allocated. This is a funding breakdown, not an estimate of your earnings.</p><label className="unit-label" htmlFor="units">Membership units <strong>{units}</strong></label><input id="units" type="range" min="1" max="20" value={units} onChange={e=>setUnits(+e.target.value)}/><div className="range-labels"><span>1 unit</span><span>20 units</span></div><div className="contribution">Total contribution <b>${format(units*100)}</b></div></div><div className="allocation-visual"><div className="allocation-top"><span>ALLOCATION MODEL</span><span>100% ASSIGNED</span></div><div className="big-number">90<span>%</span><small>Point reward pool</small></div><div className="allocation-bar" aria-label="90% points, 5% token support, 4% builders, 1% development"><i/><i/><i/><i/></div><div className="allocation-list">{[['Point rewards',90,'mint'],['Token support',5,'white'],['Builder pools',4,'gray'],['Development',1,'dark']].map(([name,pct,color])=><div key={name}><span><i className={color}/>{name}</span><b>${format(units*pct)}</b><small>{pct}%</small></div>)}</div><p className="mini-note">The 5% token allocation funds support pools. It does not mint FTI for the member.</p></div></div></section>
 <section id="binary" className="section wrap binary-section"><Eyebrow n="03">THE BINARY PLAN</Eyebrow><div className="section-heading"><h2>Two branches.<br/><em>Understand the balance.</em></h2><p>Experiment with branch volume and point caps. The smaller branch determines raw matches; the current cap determines paid points.</p></div><div className="binary-grid"><div className="binary-demo"><div className="panel-header"><span>POINT MATCHING LAB</span><span className="subtle-chip">Illustrative</span></div><Tree left={left} right={right}/><div className="input-grid"><label>Left volume<input type="number" min="0" max="1000000" value={left} onChange={e=>setLeft(Math.min(1000000,Math.max(0,Math.floor(+e.target.value||0))))}/></label><label>Right volume<input type="number" min="0" max="1000000" value={right} onChange={e=>setRight(Math.min(1000000,Math.max(0,Math.floor(+e.target.value||0))))}/></label><label>Rank<select value={rank} onChange={e=>setRank(+e.target.value)}>{['Member','Builder I','Builder II','Builder III','Builder IV'].map((s,i)=><option value={i} key={s}>{s}</option>)}</select></label><label>Protection level<select value={level} onChange={e=>setLevel(+e.target.value)}>{[0,1,2,3].map(i=><option key={i} value={i}>Level {i}</option>)}</select></label></div><div className="results" aria-live="polite"><div><span>Paid points</span><b>{paid}</b></div><div><span>Matched excess</span><b>{raw-paid}</b></div><div><span>Volume carried</span><b>{Math.abs(left-right)}<small> {left>right?'L':left<right?'R':''}</small></b></div></div><p className="mini-note">Matched excess is consumed. Paid points are not a dollar payout or an income guarantee.</p></div><div className="binary-steps">{[['01','Start with a position','Registration places a new wallet beneath an existing member, filling the left position before the right.'],['02','Match eligible volume','Purchased units propagate through ancestors. Balanced volume creates raw matches; rank and protection caps apply.'],['03','Allocate funded rewards','The pool is divided by total paid points. An individual payout depends on their share of those points.'],['04','Claim from your wallet','Allocated cash is claimed by its beneficiary. Unbalanced branch volume remains for a later settlement.']].map(([n,title,body])=><article key={n}><span>{n}</span><div><h3>{title}</h3><p>{body}</p></div></article>)}<a href={REVIEW} target="_blank" rel="noopener noreferrer" className="review-link">Read the economic review and known limitations</a></div></div></section>
 <RankExplorer rank={rank} setRank={setRank} level={level} setLevel={setLevel}/><Settlement/><section id="token" className="token-section"><div className="wrap"><div className="token-title"><Eyebrow n="06">FTI TOKEN MECHANICS</Eyebrow><h2>Price follows<br/><em>real backing.</em></h2><p>V2 starts with zero supply. Purchases add reserves and mint backed shares; redemptions burn user tokens and pay from recorded reserves subject to the live quote and protection limits.</p></div><div className="token-layout"><div className="curve-panel"><div className="panel-header"><span>CURVE EXPLORER</span><div className="segmented" aria-label="Curve direction"><button onClick={()=>setMode('buy')} aria-pressed={mode==='buy'}>Buy</button><button onClick={()=>setMode('sell')} aria-pressed={mode==='sell'}>Sell</button></div></div><div className="curve-text"><b>{mode==='buy'?'Reserve in. Tokens minted.':'Tokens burned. Reserve out.'}</b><span>Conceptual illustration · not live market data</span></div><CurveChart mode={mode}/><div className="curve-caption"><span>{mode==='buy'?'Gross collateral enters reserve; only 98% of value is represented by new user + animal shares.':'Payout reflects the base fee, size impact and current reserve/share value.'}</span><b>REAL RESERVE</b></div></div><div className="token-facts"><div><span>01 / BACKING</span><h3>Real reserve / real supply</h3><p>There is no virtual reserve in V2. Before the first actual token purchase, supply is zero; binary support never mints FTI.</p></div><div><span>02 / EXIT</span><h3>No vesting lock</h3><p>Holders use min-out and deadline protection. Normal large exits face transparent size and hourly reserve controls instead of a 30/90-day lock.</p></div><div><span>03 / ANIMALS</span><h3>Backed support shares</h3><p>One percentage point of each 3% buy/sell base fee is represented as fully-backed FTI split between two configured animal-support wallets.</p></div></div></div></div></section>
 <TokenRules/><Guide app={APP}/>
 <section id="development" className="development-section"><div className="wrap"><Eyebrow n="09">OPEN DEVELOPMENT</Eyebrow><div className="section-heading"><h2>See what works.<br/><em>Know what comes next.</em></h2><p>Development status should be as visible as the product. Explore the source and the issues that still need to be resolved.</p></div><div className="development-grid"><article><span className="stage-label">AVAILABLE FOR TESTING</span><h3>The current testnet</h3><ul><li>Binary placement and unit purchases</li><li>Point allocation and reward claims</li><li>Token purchases, slippage controls and redemptions</li><li>Public contract source and tests</li></ul><External href={REPO} className="line-link">View source code</External></article><article><span className="stage-label candidate">TOKEN V2 CANDIDATE</span><h3>Zero start. No vesting locks.</h3><ul><li>3% buy/sell base fee; 1 percentage point supports animals</li><li>Slippage + anti-whale sell protection</li><li>5-of-7 redemption-only emergency vote</li><li>Separate deployment and audit required</li></ul><External href={REPO+'/blob/fix/zero-start-animal-protection/docs/TOKEN-V2.md'} className="line-link">Review Token V2</External></article><article className="review-card"><span className="stage-label review">REVIEW IN PROGRESS</span><h3>Questions we must resolve</h3><ul><li>Carried-pool reward concentration</li><li>Multi-wallet and sale-splitting behavior</li><li>Settlement capacity at larger scale</li><li>Independent security audit</li></ul><External href={REVIEW} className="line-link">Read the findings</External></article></div><div className="contract-row"><div><small>CURRENT LEGACY TESTNET TOKEN · CHAIN 97</small><code>0x127bEEe5c89fDf42Bb056BBD5D4491982880eE91</code></div><div><button className="button small outline" onClick={copy} aria-live="polite">{copied?'Copied':'Copy address'}</button><External className="button small outline" href="https://testnet.bscscan.com/address/0x127bEEe5c89fDf42Bb056BBD5D4491982880eE91">Explorer</External></div></div></div></section>
 <Resources/>
 <section id="faq" className="section wrap faq-section"><div><Eyebrow n="11">A FEW IMPORTANT ANSWERS</Eyebrow><h2>Clarity<br/><em>comes first.</em></h2><p>Understand the rules and limitations before you connect a wallet.</p><External href={REPO} className="text-link">Explore the documentation</External></div><div className="faqs"><label className="faq-search">Search the answers<input type="search" value={faqSearch} onChange={e=>setFaqSearch(e.target.value)} placeholder="Try ranks, fees or rewards"/></label>{faq.every(([q,a])=>!(q+' '+a).toLowerCase().includes(faqSearch.trim().toLowerCase()))&&<p className="no-results" role="status">No matching answers. Try a shorter phrase or <button onClick={()=>setFaqSearch('')}>clear your search</button>.</p>}{faq.map(([q,a],i)=>({q,a,i})).filter(({q,a})=>(q+' '+a).toLowerCase().includes(faqSearch.trim().toLowerCase())).map(({q,a,i})=><article key={q} className={opened===i?'expanded':''}><h3><button id={'question-'+i} aria-expanded={opened===i} aria-controls={'answer-'+i} onClick={()=>setOpened(opened===i?-1:i)}>{q}<span aria-hidden="true">{opened===i?'−':'+'}</span></button></h3><div id={'answer-'+i} role="region" aria-labelledby={'question-'+i} hidden={opened!==i}><p>{a}</p></div></article>)}</div></section>
 <section className="closing wrap"><div className="closing-top"><Mark/><span>UNDERSTAND. EXPLORE. VERIFY.</span></div><h2>The next step starts<br/>with <em>understanding.</em></h2><div className="closing-actions"><External className="button primary" href={APP}>Explore FTI testnet</External><External className="button outline" href={REPO}>Read the source</External></div><p>Test assets only. No guaranteed income, token price or principal repayment.</p></section></main>
 <footer className="wrap"><div className="footer-top"><a href="#" className="logo"><Mark/>FTI Protocol</a><p>An open look at the rules<br/>behind the system.</p><div><a href="#protocol">Protocol</a><a href="#binary">Binary plan</a><a href="#token">Token mechanics</a></div><div><a href={APP}>Member dashboard</a><a href={TOKEN}>FTI token site</a><a href={ADMIN}>Administration</a><a href="#resources">Resources & contracts</a><a href="#development">Development</a><a href="#faq">FAQs</a><External href={REPO}>GitHub</External></div></div><div className="footer-word">FTI PROTOCOL<span>©</span></div><div className="footer-bottom"><span>© {new Date().getFullYear()} FTI Protocol</span><span>BNB SMART CHAIN TESTNET</span><span>ENGLISH / EN</span></div></footer></>
}
createRoot(document.getElementById('root')).render(<App/>);
