import React,{useEffect,useState} from 'react';
import {t,language} from '../../frontend/locale.js';
import {siteLinks} from '../../frontend/site-links.js';
const links=siteLinks(location.href),pair=(en,fa)=>t(en,fa);
const sections=[
 ['Purpose','هدف', 'FTI connects membership, funded binary rewards and a reserve token through one on-chain deployment. This document describes the continuity testnet model, not an audited mainnet release.','FTI عضویت، پاداش باینری تأمین‌شده و توکن مبتنی بر ذخیره را در یک مجموعه قرارداد متصل می‌کند. این سند مدل Continuity تست‌نت را توضیح می‌دهد؛ نسخه حسابرسی‌شده شبکه اصلی نیست.'],
 ['Membership and ranks','عضویت و رنک‌ها','One membership unit costs 100 test USD. Repeat purchases add units to the same wallet position. Placement fills the sponsor’s left slot, then right. Builder thresholds are 100, 200, 500 and 1,000 balanced lifetime points.','هر واحد عضویت ۱۰۰ دلار آزمایشی است. خرید مجدد، واحدهای همان جایگاه ولت را افزایش می‌دهد. چیدمان ابتدا سمت چپ معرف و سپس راست است. آستانه رنک‌های بیلدر ۱۰۰، ۲۰۰، ۵۰۰ و ۱۰۰۰ پوینت متوازن کل است.'],
 ['Contribution allocation','تقسیم مبلغ عضویت','The 100 USD unit allocates 90% to binary point funding, 5% to token price support, 4% to monthly Builder funding and 1% to development. Charity allocation is not present.','از مبلغ هر واحد، ۹۰٪ به تأمین پوینت باینری، ۵٪ به حمایت قیمت توکن، ۴٪ به پاداش ماهانه بیلدر و ۱٪ به توسعه تخصیص می‌یابد. سهم خیریه وجود ندارد.'],
 ['Hourly points','پوینت و تسویه ساعتی','Paid points require 20 USD gross funded backing. Calculated point value below 16 USD activates protection layers. Payment is bounded by rank caps and attributed branch credit; unpaid matched volume is retained. A stored point value alone does not prove a cash transfer.','پوینت پرداختی به ۲۰ دلار پشتوانه ناخالص تأمین‌شده نیاز دارد. ارزش محاسباتی زیر ۱۶ دلار لایه‌های حفاظت را فعال می‌کند. پرداخت تابع سقف رنک و اعتبار منتسب به شاخه‌ها است؛ حجم متوازن پرداخت‌نشده حفظ می‌شود. عدد ارزش پوینت به‌تنهایی اثبات واریز نقدی نیست.'],
 ['Token pricing','قیمت‌گذاری توکن','With nonzero supply, internal spot price equals pricing reserve divided by token supply. Support reserve stays separate. The first normal cycle opens at 0.10 USD and later normal cycles at 0.20 USD. There is no premint or time lock.','در عرضه غیرصفر، قیمت داخلی برابر ذخیره قیمت‌گذاری تقسیم بر عرضه توکن است. صندوق حمایت جدا می‌ماند. چرخه نخست عادی از ۰٫۱۰ دلار و چرخه‌های عادی بعدی از ۰٫۲۰ دلار آغاز می‌شوند. پیش‌صدور و قفل زمانی وجود ندارد.'],
 ['Purchases and fees','خرید و کارمزدها','Purchases are recalculated in 500 USD steps, at most 128 steps (64,000 USD) per transaction. Ordinary buy/sell fee is 3%. Base purchase allowance per unit is 500 / 600 / 700 / 800 / 1,000 USD by rank; Builder multipliers increase at tenfold price milestones, capped at 16×. Transfers burn 3% rounded up.','خرید در پله‌های ۵۰۰ دلاری با قیمت جدید محاسبه می‌شود؛ هر تراکنش حداکثر ۱۲۸ پله، معادل ۶۴٬۰۰۰ دلار دارد. کارمزد عادی خرید و فروش ۳٪ است. مجوز پایه خرید هر واحد به‌ترتیب رنک ۵۰۰، ۶۰۰، ۷۰۰، ۸۰۰ و ۱۰۰۰ دلار است؛ ضریب بیلدر در نقاط رشد ده‌برابری افزایش می‌یابد و حداکثر ۱۶× است. انتقال ۳٪ را با گردکردن رو به بالا می‌سوزاند.'],
 ['Sales and finite support','فروش و حمایت محدود','Gross sales up to 500 USD bypass ordinary sale limits. Larger ordinary sales face a 5% current-reserve single-sale limit and a 20% hourly net-outflow limit. Full-supply exits are exempt; payout goes to the seller and final fee/remaining support to development. Support injections use available funding after a recorded-high drawdown.','فروش ناخالص تا ۵۰۰ دلار از سقف‌های عادی معاف است. فروش عادی بزرگ‌تر تابع سقف ۵٪ ذخیره جاری در هر فروش و ۲۰٪ خروج خالص ساعتی است. خروج کل عرضه معاف است؛ دریافتی به فروشنده و کارمزد نهایی و حمایت باقیمانده به توسعه می‌رود. تزریق حمایت پس از افت از سقف ثبت‌شده، از موجودی قابل تأمین انجام می‌شود.'],
 ['Auto-buy and payouts','خرید خودکار و پرداخت پاداش','An eligible Builder can enable auto-buy using 5% of their hourly reward, not monthly Builder rewards. Failed purchases preserve the balance for retry. The Keeper progresses settlement and payment queues; reward transfers are processed in bounded batches.','بیلدر واجد شرایط می‌تواند اتوبای را از ۵٪ پاداش ساعتی خودش فعال کند؛ منبع آن پاداش ماهانه بیلدر نیست. موجودی خرید ناموفق برای تلاش مجدد حفظ می‌شود. Keeper صف تسویه و پرداخت را پردازش می‌کند؛ انتقال پاداش در دسته‌های محدود انجام می‌شود.'],
 ['Governance and continuity','شورا و تداوم داده','The council requires five approvals from seven guardians. Ordinary governance uses the configured timelock, initially 72 hours. Proxy upgrade and recovery controls require governance authorization; opening a council subdomain grants no authority. Recovery freezes, checkpoints and migration require verified procedures; preservation is not automatic merely because a new contract is deployed.','شورا به پنج رأی از هفت نگهبان نیاز دارد. حاکمیت عادی از قفل زمانی تنظیم‌شده، در استقرار اولیه ۷۲ ساعت، استفاده می‌کند. ارتقای پروکسی و بازیابی نیازمند مجوز حاکمیت‌اند؛ ورود به ساب‌دامنه شورا اختیار نمی‌دهد. توقف بازیابی، چک‌پوینت و مهاجرت به روند تأییدشده نیاز دارند؛ صرف ایجاد قرارداد جدید انتقال خودکار داده و پول را انجام نمی‌دهد.'],
 ['Data and limitations','داده‌ها و محدودیت‌ها','The market displays recent execution-price candles and recent-block notional volume, not complete 24-hour exchange history. tUSD is MockUSD and has no real dollar backing. Finite support, RPC outages, software defects and governance risks remain; independent audit and operational checks precede mainnet use.','بازار، کندل قیمت اجرای معاملات و حجم بلاک‌های اخیر را نمایش می‌دهد؛ این تاریخچه کامل ۲۴ ساعته صرافی نیست. tUSD همان MockUSD است و پشتوانه دلار واقعی ندارد. محدودیت حمایت، قطعی RPC، باگ نرم‌افزاری و ریسک حاکمیت باقی است؛ استفاده در شبکه اصلی به حسابرسی مستقل و بررسی عملیاتی نیاز دارد.']
];
const phases=[
 ['01','Available in current code','موجود در کد فعلی','Membership, binary settlement, staged token trades, transfer burn and governance controls. Public TESTNET verification is tracked separately.','عضویت، تسویه باینری، خرید پلکانی، فروش، سوزاندن انتقال و کنترل‌های شورا. تأیید اجرای عمومی تست‌نت جداگانه پیگیری می‌شود.'],
 ['02','This interface release','نسخه فعلی رابط کاربری','Separate member, token and council entry points; documentation and responsive pure-black layouts. DNS and TLS activation remains a server installation step.','ورودی جدا برای اعضا، توکن و شورا؛ مستندات و طراحی مشکی واکنش‌گرا. فعال‌سازی DNS و SSL مرحله نصب سرور است.'],
 ['03','Validation gate','مرحله اعتبارسنجی','Complete network stress tests, reconcile actual reward transfers, test recovery/migration with balances, and collect a durable market history.','تکمیل تست فشار شبکه، تطبیق واریز واقعی پاداش، تست بازیابی و مهاجرت با موجودی و جمع‌آوری تاریخچه پایدار بازار.'],
 ['04','Before mainnet','پیش از شبکه اصلی','Independent security audit, remediation, council key custody review and signed operational readiness. No guaranteed launch date or exchange listing.','حسابرسی امنیتی مستقل، رفع یافته‌ها، بررسی نگهداری کلید شورا و تأیید آمادگی عملیاتی. زمان عرضه یا فهرست‌شدن در صرافی تضمین نشده است.']
];
export function PublicSite(){
 const page=location.pathname==='/whitepaper/'?'whitepaper':location.pathname==='/roadmap/'?'roadmap':'token';
 const[cfg,setCfg]=useState(null),[state,setState]=useState(null),[error,setError]=useState(false),[menu,setMenu]=useState(false);
 useEffect(()=>{document.title=page==='token'?'FTI Token':page==='whitepaper'?'FTI Whitepaper':'FTI Roadmap';const abort=new AbortController();async function load(){try{const results=await Promise.all(['/api/config','/api/state'].map(async p=>{const r=await fetch(p,{signal:abort.signal});if(!r.ok)throw Error();return r.json();}));setCfg(results[0]);setState(results[1]);setError(false);}catch(e){if(e.name!=='AbortError')setError(true);}}load();const timer=setInterval(load,30000);return()=>{abort.abort();clearInterval(timer);};},[page]);
 const format=v=>v===undefined?'—':(Number(v)/1e18).toLocaleString('en-US',{maximumFractionDigits:6});
 return <div className="public-site"><header className="site-header"><div className="wrap header-inner"><a className="brand" href={links.token}><img src="/app/favicon.svg" width="36" height="36" alt=""/><span>FTI<small>TOKEN</small></span></a><button className="menu-button" aria-expanded={menu} aria-controls="public-nav" onClick={()=>setMenu(!menu)}>{pair('Menu','منو')}</button><nav id="public-nav" className={menu?'open':''}>{[[links.main,'Protocol','پروتکل'],[links.whitepaper,'Whitepaper','وایت‌پیپر'],[links.roadmap,'Roadmap','رودمپ'],[links.council,'Council','شورا']].map(([href,en,fa])=><a key={href} href={href}>{pair(en,fa)}</a>)}</nav><div className="header-actions"><button className="language" onClick={()=>{localStorage.setItem('fti-language',language==='fa'?'en':'fa');location.reload();}}>{language==='fa'?'EN':'FA'}</button><a className="button compact" href={links.trade}>{pair('Trade FTI','خرید و فروش')}</a></div></div></header>
 <main>{page==='token'?<><section className="wrap token-public-hero"><div><span className="pill">FTI / BNB TESTNET</span><h1>{pair('Understand the reserve.','ذخیره را ببینید.')}<br/><span>{pair('Own your next move.','آگاهانه معامله کنید.')}</span></h1><p>{pair('An on-chain reserve token with visible funding, staged purchases and wallet-controlled transactions.','توکن مبتنی بر ذخیره روی شبکه؛ با پشتوانه قابل مشاهده، خرید پلکانی و تراکنش با تأیید ولت شما.')}</p><div className="actions"><a className="button" href={links.trade}>{pair('Open the market','ورود به بازار')}</a><a className="button outline" href={links.whitepaper}>{pair('Read the whitepaper','مطالعه وایت‌پیپر')}</a></div><small>{pair('Testnet assets · no real USD backing','دارایی تست‌نت · بدون پشتوانه دلار واقعی')}</small></div><img src="/protocol-ring.webp" alt=""/></section>
 <section className="wrap public-stats" aria-label={pair('Live contract data','داده زنده قرارداد')}>{[[pair('Spot · tUSD','قیمت · tUSD'),format(state?.price)],[pair('Reserve · tUSD','ذخیره · tUSD'),format(state?.reserve)],[pair('Support · tUSD','حمایت · tUSD'),format(state?.bb)],[pair('Supply · FTI','عرضه · FTI'),format(state?.supply)]].map(([title,value])=><article key={title}><span>{title}</span><strong>{value}</strong></article>)}</section>{error&&<p className="wrap feed-warning" role="status">{pair('Live data is temporarily unavailable.','داده زنده موقتاً در دسترس نیست.')}</p>}
 <section className="wrap section"><div className="section-heading"><h2>{pair('Mechanics you can inspect.','قوانین قابل بررسی.')}</h2></div><div className="public-feature-grid">{[[pair('500 USD steps','پله‌های ۵۰۰ دلاری'),pair('Each step uses its new reserve quote; transaction and wallet allowances apply.','هر پله با نرخ جدید ذخیره محاسبه می‌شود؛ مجوز ولت و سقف تراکنش اعمال می‌شوند.')],[pair('3% trade fee','۳٪ کارمزد معامله'),pair('Quote, minimum output and deadline are explicit before wallet confirmation.','نرخ، حداقل دریافتی و مهلت پیش از تأیید ولت مشخص‌اند.')],[pair('3% transfer burn','۳٪ سوزاندن انتقال'),pair('The recipient receives 97% of the total debit; rounding applies.','گیرنده ۹۷٪ برداشت کل را دریافت می‌کند؛ گردکردن اعمال می‌شود.')]].map(([title,copy])=><article key={title}><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
 <section className="wrap section public-feature-grid">{[[links.whitepaper,'01','Whitepaper','وایت‌پیپر','Economics, fees, settlement and governance.','اقتصاد توکن، کارمزد، تسویه و حاکمیت.'],[links.roadmap,'02','Roadmap','رودمپ','Current capabilities and the checks still ahead.','قابلیت‌های فعلی و مراحل بررسی باقی‌مانده.'],[links.member,'03','Your dashboard','پنل شما','Membership, genealogy and your rewards.','عضویت، ژنولوژی و پاداش‌های شما.']].map(([href,n,en,fa,copy,faCopy])=><a key={href} href={href} className="public-resource"><span>{n}</span><h3>{pair(en,fa)}</h3><p>{pair(copy,faCopy)}</p><b>↗</b></a>)}</section>
 <section className="wrap section"><h2>{pair('Active deployment','قراردادهای فعال')}</h2><div className="contracts">{['token','binary','council','timelock'].map(key=><article key={key}><b>{key}</b>{cfg?.[key]?<a className="address" href={cfg.chainId===97?'https://testnet.bscscan.com/address/'+cfg[key]+'#code':undefined} target="_blank" rel="noreferrer">{cfg[key]}</a>:<span>—</span>}</article>)}</div></section></>:<>
 <section className="wrap document-intro"><span className="pill">FTI · CONTINUITY · TESTNET</span><h1>{page==='whitepaper'?pair('FTI Whitepaper','وایت‌پیپر FTI'):pair('FTI Roadmap','رودمپ FTI')}</h1><p>{pair('Version 1 · 10 October 2026 · matches the current continuity code.','نسخه ۱ · ۱۰ اکتبر ۲۰۲۶ · منطبق با کد فعلی Continuity.')}</p><div className="actions"><button className="button outline" onClick={()=>window.print()}>{pair('Print / save PDF','چاپ / ذخیره PDF')}</button><a className="button" href={links.trade}>{pair('Open market','ورود به بازار')}</a></div></section>
 {page==='whitepaper'?<div className="wrap document-layout"><nav className="document-toc" aria-label={pair('Contents','فهرست')}>{sections.map(([en,fa],i)=><a key={en} href={'#doc-'+i}>{String(i+1).padStart(2,'0')} · {pair(en,fa)}</a>)}</nav><article className="document-content">{sections.map(([en,fa,copy,faCopy],i)=><section id={'doc-'+i} key={en}><span className="kicker">{String(i+1).padStart(2,'0')}</span><h2>{pair(en,fa)}</h2><p>{pair(copy,faCopy)}</p></section>)}</article></div>:<section className="wrap roadmap-list">{phases.map(([n,en,fa,copy,faCopy])=><article key={n}><span className="phase-number">{n}</span><div><h2>{pair(en,fa)}</h2><p>{pair(copy,faCopy)}</p></div></article>)}</section>}
 </>}</main><footer className="wrap"><a className="brand" href={links.main}>FTI <small>PROTOCOL</small></a><nav>{[[links.member,'Members','اعضا'],[links.token,'Token','توکن'],[links.council,'Council','شورا'],[links.whitepaper,'Whitepaper','وایت‌پیپر'],[links.roadmap,'Roadmap','رودمپ']].map(([href,en,fa])=><a key={href} href={href}>{pair(en,fa)}</a>)}</nav><small>BNB TESTNET · 97</small></footer></div>;
}
