import {test,before,beforeEach,after} from 'node:test';import assert from 'node:assert/strict';import ganache from 'ganache';import {BrowserProvider,parseEther as E} from 'ethers';import {deploySuite,checkAccounting} from '../scripts/lib.mjs';
let engine,p,s,signers,snapshot;
before(async()=>{engine=ganache.provider({logging:{quiet:true},wallet:{totalAccounts:36},chain:{chainId:31337},miner:{blockGasLimit:30000000}});p=new BrowserProvider(engine,undefined,{cacheTimeout:-1});p.pollingInterval=10;signers=await Promise.all(Array.from({length:36},(_,i)=>p.getSigner(i)));s=await deploySuite(signers);for(const i of [15,16,17]){const w=signers[i];for(const [c,m,a]of [[s.usd,'faucet',[]],[s.usd,'approve',[s.binary.target,E('500')]],[s.binary,'addUnits',[5]],[s.usd,'approve',[s.token.target,E('400')]],[s.token,'buy',[E('400'),0,2n**64n-1n]]])await(await c.connect(w)[m](...a)).wait();}await p.send('evm_increaseTime',[31*86400]);await p.send('evm_mine',[]);snapshot=await p.send('evm_snapshot',[]);});
beforeEach(async()=>{await p.send('evm_revert',[snapshot]);snapshot=await p.send('evm_snapshot',[]);});after(async()=>{p.destroy();await engine.disconnect();});
async function fails(fn){await assert.rejects(async()=>{const tx=await fn();if(tx?.wait)await tx.wait();});}
async function order(price='0.01'){const now=(await p.getBlock('latest')).timestamp;await(await s.token.connect(signers[15]).createExit(E('100'),E('50'),E(price),900,now+86400)).wait();}
async function invariant(){await checkAccounting(s);const R=await s.token.reserve(),S=await s.token.curveSupply(),V=await s.token.V(),S0=await s.token.S0();assert((R+V)*S0**5n>=V*S**5n,'exact k invariant');}
test('all-wallet selloff consumes at most the shared opening support budgets and pays all holders',async()=>{let bb=0n,fl=0n,limitBB,limitFL,end;for(const i of [15,16,17]){const bal=await s.token.balanceOf(s.addresses[i]);const tx=await(await s.token.connect(signers[i]).sell(bal,0,2n**64n-1n)).wait();for(const l of tx.logs){let e;try{e=s.token.interface.parseLog(l);}catch{}if(e?.name==='SupportBudgetOpened'){assert.equal(limitBB,undefined);limitBB=e.args[1];limitFL=e.args[2];end=e.args[0];}if(e?.name==='Supported'){bb+=e.args[0];fl+=e.args[1];}}await invariant();assert.equal(await s.token.supportWindowEnd(),end);}assert(bb>0n);assert(bb<=limitBB&&fl<=limitFL);assert.equal(await s.token.totalSupply(),0n);});
test('split sales cannot replenish support budget within the window',async()=>{for(let i=0;i<6;i++){const w=signers[15+i%3];await(await s.token.connect(w).sell(E('25'),0,2n**64n-1n)).wait();const b=await s.token.buybackBudget(),f=await s.token.floorBudget(),end=await s.token.supportWindowEnd();await(await s.token.connect(w).sell(E('25'),0,2n**64n-1n)).wait();assert((await s.token.buybackBudget())<=b);assert((await s.token.floorBudget())<=f);assert.equal(await s.token.supportWindowEnd(),end);await invariant();}});
test('reserved tokens cannot transfer or sell; only owner can cancel; cancellation releases balance',async()=>{await order();const available=await s.token.available(s.addresses[15]);await fails(()=>s.token.connect(signers[15]).sell(available+1n,0,2n**64n-1n));await fails(()=>s.token.connect(signers[15]).transfer(s.addresses[16],available+1n));await fails(()=>s.token.connect(signers[16]).cancelExit(0));await(await s.token.connect(signers[15]).cancelExit(0)).wait();assert.equal(await s.token.reservedExit(s.addresses[15]),0n);assert.equal(await s.token.available(s.addresses[15]),await s.token.unlocked(s.addresses[15]));await invariant();});
test('permissionless chunk pays only owner, interval prevents early replay, final chunk releases reservation',async()=>{await order();const ownerBefore=await s.usd.balanceOf(s.addresses[15]),callerBefore=await s.usd.balanceOf(s.addresses[16]);await(await s.token.connect(signers[16]).executeExit(0)).wait();assert((await s.usd.balanceOf(s.addresses[15]))>ownerBefore);assert.equal(await s.usd.balanceOf(s.addresses[16]),callerBefore);assert.equal(await s.token.reservedExit(s.addresses[15]),E('50'));await fails(()=>s.token.executeExit(0));await p.send('evm_increaseTime',[901]);await p.send('evm_mine',[]);await(await s.token.executeExit(0)).wait();assert.equal(await s.token.reservedExit(s.addresses[15]),0n);await fails(()=>s.token.executeExit(0));await invariant();});
test('price rejection and expiry preserve order; expired reservation remains cancellable',async()=>{await order('1000');await fails(()=>s.token.executeExit(0));assert.equal((await s.token.exitOrders(0)).remaining,E('100'));assert.equal(await s.token.reservedExit(s.addresses[15]),E('100'));await p.send('evm_increaseTime',[86401]);await p.send('evm_mine',[]);await fails(()=>s.token.executeExit(0));await(await s.token.connect(signers[15]).cancelExit(0)).wait();await invariant();});
test('paused token blocks execution but allows owner cancellation',async()=>{await order();await(await s.council.connect(signers[31]).propose(s.token.target,s.token.interface.encodeFunctionData('pause'))).wait();await(await s.council.connect(signers[32]).approve(0)).wait();await(await s.council.connect(signers[33]).approve(0)).wait();await(await s.council.execute(0)).wait();await fails(()=>s.token.executeExit(0));await(await s.token.connect(signers[15]).cancelExit(0)).wait();assert.equal(await s.token.reservedExit(s.addresses[15]),0n);await invariant();});
test('failed USD delivery rolls back chunk reservation, reserve and burns atomically',async()=>{await order();const before=[await s.token.reserve(),await s.token.buybackFund(),await s.token.floorFund(),await s.token.balanceOf(s.addresses[15])];await(await s.usd.setBlocked(s.addresses[15],true)).wait();await fails(()=>s.token.executeExit(0,{gasLimit:5000000}));assert.deepEqual([await s.token.reserve(),await s.token.buybackFund(),await s.token.floorFund(),await s.token.balanceOf(s.addresses[15])],before);assert.equal((await s.token.exitOrders(0)).remaining,E('100'));assert.equal(await s.token.reservedExit(s.addresses[15]),E('100'));await invariant();});
