import {JsonRpcProvider,BrowserProvider,Contract,parseEther,formatEther,ZeroAddress,ZeroHash,randomBytes,hexlify,isAddress} from '/vendor/ethers.js';
const $=s=>document.querySelector(s);const cfg=await fetch('/api/config').then(r=>r.json());const rpc=new JsonRpcProvider(location.origin+'/rpc',undefined,{cacheTimeout:-1});rpc.pollingInterval=500;
const names={binary:'BinaryPlan',token:'FTIToken',usd:'MockUSD',council:'Council',timelock:'FTITimelock'};const read={};
for(const[k,n]of Object.entries(names))read[k]=new Contract(cfg[k],await fetch('/abi/'+n).then(r=>r.json()),rpc);
let signer,address,state,busy=false;const ranks=['Member','Builder 1','Builder 2','Builder 3','Builder 4'];
const fmt=(v,d=2)=>v===undefined?'—':Number(formatEther(v)).toLocaleString('en-US',{maximumFractionDigits:d});
const integer=v=>Number(v).toLocaleString('en-US');const text=(id,v)=>{$('#'+id).textContent=v};
function status(message,error=false){$('#status').textContent=message;$('#status').classList.toggle('error',error)}
function write(k){if(!signer)throw Error('Connect your wallet first.');return read[k].connect(signer)}
async function transaction(fn){if(busy)return;busy=true;document.querySelectorAll('button').forEach(b=>b.disabled=true);try{status('Waiting for transaction approval and confirmation…');await fn();status('Transaction confirmed on-chain.');await refresh();}catch(e){status(e.reason||e.shortMessage||e.message,true)}finally{busy=false;document.querySelectorAll('button').forEach(b=>b.disabled=false)}}
async function send(promise){const tx=await promise;status('Transaction submitted; awaiting confirmation… '+tx.hash.slice(0,14));await tx.wait();}
async function approve(spender,amount){const current=await read.usd.allowance(address,spender);if(current<amount){if(current>0n)await send(write('usd').approve(spender,0));await send(write('usd').approve(spender,amount));}}
async function connect(){if(cfg.mode==='local'){signer=await rpc.getSigner($('#local-accounts').value);}else{if(!window.ethereum)throw Error('A wallet extension or wallet browser is required.');const provider=new BrowserProvider(window.ethereum);await provider.send('eth_requestAccounts',[]);if(Number((await provider.getNetwork()).chainId)!==cfg.chainId)throw Error('Switch your wallet to BNB Testnet, chain ID '+cfg.chainId+'.');signer=await provider.getSigner();}address=await signer.getAddress();text('connect',address.slice(0,6)+'…'+address.slice(-4));await refresh();}
$('#connect').onclick=()=>connect().catch(e=>status(e.message,true));
if(window.ethereum){window.ethereum.on?.('accountsChanged',()=>{signer=null;address=null;text('connect','Connect wallet');refresh();});window.ethereum.on?.('chainChanged',()=>location.reload());}
if(cfg.mode==='local'){
 $('#local-accounts').hidden=false;$('#dev-controls').hidden=false;
 cfg.accounts.forEach((a,i)=>{const o=document.createElement('option');o.value=a;o.textContent=`${i+1}. ${i<31?'Genesis':i<36?'Council':'New member'} ${a.slice(0,6)}`;$('#local-accounts').append(o);});$('#local-accounts').onchange=()=>connect().catch(e=>status(e.message,true));
}
text('network-name',cfg.mode==='local'?'Local chain · 31337':'BNB Testnet · 97');
const titles={overview:'Protocol overview',network:'Network & membership',trade:'Trade FTI',activity:'Protocol activity',admin:'Governance & settlement'};
document.querySelectorAll('[data-page]').forEach(button=>button.onclick=()=>{document.querySelectorAll('.page').forEach(p=>p.hidden=p.id!==button.dataset.page);document.querySelectorAll('[data-page]').forEach(b=>b.classList.toggle('active',b===button));text('page-title',titles[button.dataset.page]);if(button.dataset.page==='activity')loadEvents();if(button.dataset.page==='admin')loadProposals();});
$('#theme').onclick=()=>{document.body.classList.toggle('light');localStorage.setItem('fti-theme',document.body.classList.contains('light')?'light':'dark');};if(localStorage.getItem('fti-theme')==='light')document.body.classList.add('light');
async function refresh(){const response=await fetch('/api/state'+(address?'?wallet='+address:''));const d=await response.json();if(!response.ok)throw Error(d.error);state=d;
 for(const[id,value]of Object.entries({price:fmt(d.price,6),reserve:fmt(d.reserve),reserve2:fmt(d.reserve),members:integer(d.count),'point-pool':fmt(d.pointPool),buyback:fmt(d.bb),floor:fmt(d.floor),supply:fmt(d.supply),epoch:'Epoch '+integer(d.epoch),phase:['Accepting deposits','Matching points','Allocating rewards'][d.phase],protection:integer(d.level),'epoch-end':new Date(Number(d.epochEnd)*1000).toLocaleString('en-US'),accounting:d.account1[0]===d.account1[1]&&d.account2[0]===d.account2[1]?'Balanced':'Review required',queue:`Volume queue: ${d.jobCursor} of ${d.jobCount} · Settlement phase: ${d.phase} · Member cursor: ${d.cursor}`}))text(id,value);
 const w=d.wallet;
 for(const[id,value]of Object.entries({claimable:w?fmt(w.claimable):'—',rank:w?ranks[w.rank]:'No wallet connected','wallet-address':address||'No wallet connected','usd-balance':w?fmt(w.usdBalance):'—','fti-balance':w?fmt(w.ftiBalance,5):'—',unlocked:w?fmt(w.unlocked,5):'—',allowance:w?fmt(w.remaining):'—',units:w?integer(w.units):'—',lifetime:w?`${w.lifetimeL} / ${w.lifetimeR}`:'—',carry:w?`${w.carryL} / ${w.carryR}`:'—','auto-pending':w?fmt(w.autoPending):'—'}))text(id,value);
 $('#tree').replaceChildren();for(const[label,key]of [['Sponsor','parent'],['Left branch','left'],['Right branch','right']]){const node=document.createElement('div');node.textContent=label;const a=document.createElement('small');a.textContent=w&&w[key]!==ZeroAddress?w[key]:'Empty';node.append(a);$('#tree').append(node);}
 $('#locks').replaceChildren();if(w?.locks.length){for(const l of w.locks){const tr=document.createElement('tr');for(const val of [fmt(l.amount,5),integer(l.clock),new Date(Number(l.deadline)*1000).toLocaleDateString('en-US'),BigInt(d.clock)>=BigInt(l.clock)||d.timestamp>=Number(l.deadline)?'Unlocked':'Locked']){const td=document.createElement('td');td.textContent=val;tr.append(td);}$('#locks').append(tr);}}else{const tr=document.createElement('tr');const td=document.createElement('td');td.colSpan=4;td.textContent='No lock tranches recorded.';tr.append(td);$('#locks').append(tr);}
 if(w&&!$('#auto-form').contains(document.activeElement)){$('#auto-form').elements.enabled.checked=w.autoEnabled;if(BigInt(w.maxAutoPrice)>0n)$('#auto-form').elements.price.value=formatEther(w.maxAutoPrice);}
}
$('#claim').onclick=()=>transaction(()=>send(write('binary').claim()));$('#faucet').onclick=()=>transaction(()=>send(write('usd').faucet()));
$('#register-form').onsubmit=e=>{e.preventDefault();transaction(async()=>{const f=e.target;const n=BigInt(f.elements.units.value);if(n<1n||n>1000000n)throw Error('Invalid unit count.');if(!address)throw Error('Connect your wallet.');if(!state.wallet.exists&&!isAddress(f.elements.sponsor.value))throw Error('Enter a sponsor address.');await approve(cfg.binary,n*parseEther('100'));await send(state.wallet.exists?write('binary').addUnits(n):write('binary').register(f.elements.sponsor.value,n));});};
$('#auto-form').onsubmit=e=>{e.preventDefault();transaction(()=>send(write('binary').setAutoBuy(e.target.elements.enabled.checked,parseEther(e.target.elements.price.value))));};
$('#execute-auto').onclick=()=>transaction(()=>send(write('binary').executeAuto(address,BigInt(state.wallet.autoPending))));$('#release-auto').onclick=()=>transaction(()=>send(write('binary').releaseAutoToCash()));
for(const kind of ['buy','sell']){
 const form=$('#'+kind+'-form');let debounce;
 form.elements.amount.oninput=()=>{clearTimeout(debounce);debounce=setTimeout(async()=>{try{const amount=parseEther(form.elements.amount.value);if(amount<=0n)throw Error();if(kind==='buy'){const q=await read.token.quoteBuy(amount);text('buy-quote','Estimated output: '+fmt(q,6)+' FTI');}else{const q=await read.token.quoteSell(amount);text('sell-quote','Net proceeds: '+fmt(q[0],6)+' test USD · Fee '+Number(q[1])/100+'%');}}catch{text(kind+'-quote','Enter a valid amount.');}},250);};
 form.onsubmit=e=>{e.preventDefault();transaction(async()=>{const a=parseEther(form.elements.amount.value);const slip=Math.round(Number(form.elements.slippage.value)*100);if(a<=0n||slip<0||slip>500)throw Error('Invalid amount or slippage.');const deadline=BigInt(state.timestamp+1200);if(kind==='buy'){const quote=await read.token.quoteBuy(a);await approve(cfg.token,a);await send(write('token').buy(a,quote*BigInt(10000-slip)/10000n,deadline));}else{const[q]=await read.token.quoteSell(a);await send(write('token').sell(a,q*BigInt(10000-slip)/10000n,deadline));}});};
}
$('#transfer-form').onsubmit=e=>{e.preventDefault();transaction(()=>send(write('token').transfer(e.target.elements.to.value,parseEther(e.target.elements.amount.value))));};
for(const[id,method,arg]of [['volume','processVolume',50],['close-epoch','beginEpochClose'],['process-epoch','processEpoch',50],['begin-month','beginBuilderMonth'],['process-month','processBuilderMonth',50]])$('#'+id).onclick=()=>transaction(()=>send(write('binary')[method](...(arg?[arg]:[]))));
document.querySelectorAll('[data-time]').forEach(b=>b.onclick=()=>transaction(async()=>{const r=await fetch('/api/dev/time',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({seconds:Number(b.dataset.time)})});if(!r.ok)throw Error((await r.json()).error);}));
async function loadEvents(){try{const rows=await fetch('/api/events').then(r=>r.json());if(!Array.isArray(rows))throw Error(rows.error);$('#events').replaceChildren();if(!rows.length)$('#events').textContent='No events in this range.';for(const row of rows){const node=document.createElement('div');node.className='event';const title=document.createElement('strong');title.textContent=row.name+' · #'+row.block;const pre=document.createElement('pre');pre.textContent=row.args.map(a=>a.name+': '+a.value).join('\n')+'\n'+row.hash;node.append(title,pre);$('#events').append(node);}}catch(e){status(e.message,true)}}$('#refresh-events').onclick=loadEvents;
for(const[k,v]of Object.entries(names)){const el=document.createElement('div');el.textContent=v;const code=document.createElement('code');code.textContent=cfg[k];el.append(code);$('#contracts').append(el);}
async function loadProposals(){try{const count=Number(await read.council.count());$('#proposals').replaceChildren();if(!count)$('#proposals').textContent='No proposals yet.';for(let i=count-1;i>=Math.max(0,count-20);i--){const p=await read.council.proposal(i);const box=document.createElement('div');box.className='proposal';const title=document.createElement('p');title.textContent=`Proposal ${i} · ${p[2]} of 3 approvals · ${p[3]?'Executed':'Pending'}`;box.append(title);for(const[label,fn]of [['Approve',()=>write('council').approve(i)],['Execute proposal',()=>write('council').execute(i)]]){const b=document.createElement('button');b.className='secondary';b.textContent=label;b.disabled=p[3];b.onclick=()=>transaction(async()=>{await send(fn());await loadProposals();});box.append(b);}$('#proposals').append(box);}}catch(e){status(e.message,true)}}
$('#proposal-form').onsubmit=e=>{e.preventDefault();transaction(async()=>{const action=e.target.elements.action.value;let target,data;
 if(action==='pauseBinary'||action==='pauseToken'){const k=action==='pauseBinary'?'binary':'token';target=cfg[k];data=read[k].interface.encodeFunctionData('pause');}
 else{const k=action==='unpauseBinary'?'binary':'token';const inner=read[k].interface.encodeFunctionData(action==='milestone'?'advancePriceMilestone':'unpause');target=cfg.timelock;data=read.timelock.interface.encodeFunctionData('schedule',[cfg[k],0,inner,ZeroHash,hexlify(randomBytes(32)),259200]);}
 await send(write('council').propose(target,data));await loadProposals();});};
$('#timelock-form').onsubmit=e=>{e.preventDefault();transaction(async()=>{const p=await read.council.proposal(BigInt(e.target.elements.id.value));if(p[0].toLowerCase()!==cfg.timelock.toLowerCase()||!p[3])throw Error('The scheduling proposal has not been executed.');const args=read.timelock.interface.decodeFunctionData('schedule',p[1]);await send(write('timelock').execute(args[0],args[1],args[2],args[3],args[4]));});};
try{if(cfg.mode==='local')await connect();else await refresh();status('Contract data loaded.');}catch(e){status(e.message,true)}
setInterval(()=>refresh().catch(e=>status('Connection unavailable: '+e.message,true)),15000);
