import {BrowserProvider,Wallet,Contract,ContractFactory,parseEther,formatEther,getAddress,isAddress,ZeroHash,hexlify,randomBytes} from './vendor/ethers.js';
const OWNER='0x63c5B98AEfd69658B652d5F35FFda3C6c06847E3';const RPC='https://bsc-testnet.bnbchain.org';
const $=id=>document.getElementById(id);const names=['MockUSD','Council','FTITimelock','FTIToken','BinaryPlan'];const labels=['Test USD','3-of-5 council','72-hour timelock','FTI token','Binary network','Connect contracts'];
const artifacts=Object.fromEntries(await Promise.all(names.map(async n=>[n,await fetch(`artifacts/${n}.json`).then(r=>r.json())])));
const STORE='fti-testnet-97-'+OWNER.toLowerCase();let provider,mainSigner,connected,helpers=[],busy=false,state;
try{state=JSON.parse(localStorage.getItem(STORE)||'null');}catch{}
state||={version:1,chainId:97,owner:OWNER,steps:[],config:null,encrypted:null};
function save(){localStorage.setItem(STORE,JSON.stringify(state));render();}
function say(message,error=false){$('status').textContent=message;$('status').classList.toggle('error',error);}
const fmt=(x,d=6)=>Number(formatEther(x)).toLocaleString('en-US',{maximumFractionDigits:d});
const b64=bytes=>btoa(String.fromCharCode(...bytes));const un64=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
function download(name,value){const blob=new Blob([JSON.stringify(value,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),5000);}
async function key(password,salt){const material=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:310000,hash:'SHA-256'},material,{name:'AES-GCM',length:256},false,['encrypt','decrypt']);}
async function encrypt(value,password){const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12));const encrypted=await crypto.subtle.encrypt({name:'AES-GCM',iv},await key(password,salt),new TextEncoder().encode(JSON.stringify(value)));return{version:1,algorithm:'AES-256-GCM',kdf:'PBKDF2-SHA256',iterations:310000,owner:OWNER,chainId:97,salt:b64(salt),iv:b64(iv),ciphertext:b64(new Uint8Array(encrypted))};}
async function decrypt(data,password){if(data.version!==1||data.owner?.toLowerCase()!==OWNER.toLowerCase()||data.chainId!==97||data.iterations!==310000)throw Error('Backup does not match this configuration.');const plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:un64(data.iv)},await key(password,un64(data.salt)),un64(data.ciphertext));return JSON.parse(new TextDecoder().decode(plain));}
async function guardNetwork(){if(!provider)throw Error('Connect your wallet first.');if(Number(await provider.send('eth_chainId',[]))!==97)throw Error('Only testnet chain 97 is allowed.');}
async function connect(){if(!window.ethereum)throw Error('Open this link in the MetaMask or Trust Wallet browser, or a browser with a wallet extension.');await window.ethereum.request({method:'eth_requestAccounts'});try{await window.ethereum.request({method:'wallet_switchEthereumChain',params:[{chainId:'0x61'}]});}catch(e){if(e.code!==4902&&e.data?.originalError?.code!==4902)throw e;await window.ethereum.request({method:'wallet_addEthereumChain',params:[{chainId:'0x61',chainName:'BNB Smart Chain Testnet',nativeCurrency:{name:'Test BNB',symbol:'tBNB',decimals:18},rpcUrls:[RPC],blockExplorerUrls:['https://testnet.bscscan.com']}]});}provider=new BrowserProvider(window.ethereum,undefined,{cacheTimeout:-1});await guardNetwork();mainSigner=await provider.getSigner();connected=await mainSigner.getAddress();$('wallet').textContent=`${connected} · Balance: ${fmt(await provider.getBalance(connected))} tBNB`;render();await refresh();}
async function action(fn){if(busy)return;busy=true;document.querySelectorAll('button').forEach(b=>b.disabled=true);try{await fn();say('Operation completed.');await refresh();}catch(e){say(e.reason||e.shortMessage||e.message,true);}finally{busy=false;document.querySelectorAll('button').forEach(b=>b.disabled=false);}}
function render(){const list=$('steps');list.replaceChildren();for(let i=0;i<6;i++){const li=document.createElement('li'),s=state.steps[i];li.textContent=labels[i]+(s?.status==='confirmed'?' — confirmed':s?.hash?' — submitted':' — pending');li.className=s?.status==='confirmed'?'done':'';if(s?.hash){const a=document.createElement('a');a.href='https://testnet.bscscan.com/tx/'+s.hash;a.target='_blank';a.rel='noopener';a.textContent=s.hash;li.append(a);}list.append(li);}
 const selected=$('account').value;$('account').replaceChildren();const option=document.createElement('option');option.value='owner';option.textContent='Connected wallet '+(connected?.slice(0,8)||'');$('account').append(option);if(state.config)state.config.genesis.slice(1).forEach((a,i)=>{const o=document.createElement('option');o.value=String(i);o.textContent=`Helper account ${i+1}${i<4?' · Council member':''} · ${a.slice(0,8)}`;$('account').append(o);});if([...$('account').options].some(o=>o.value===selected))$('account').value=selected;
 $('backup-state').textContent=helpers.length?'30 helper accounts are unlocked in browser memory.':state.encrypted?'Encrypted backup is stored. Restore it to use helper accounts.':'No helper accounts prepared.';
 $('addresses').replaceChildren();for(let i=0;i<5;i++){const s=state.steps[i];if(s?.status==='confirmed'){const el=document.createElement('div');el.className='contract';el.textContent=labels[i];const a=document.createElement('a');a.href='https://testnet.bscscan.com/address/'+s.address;a.target='_blank';a.rel='noopener';a.textContent=s.address;el.append(a);$('addresses').append(el);}}
}
function getContract(index,signer=provider){const step=state.steps[index];if(step?.status!=='confirmed')throw Error('Contract deployment is not complete yet.');return new Contract(step.address,artifacts[names[index]].abi,signer);}
async function accountSigner(){await guardNetwork();if($('account').value==='owner')return mainSigner;const i=Number($('account').value);if(!helpers[i])throw Error('Restore the encrypted backup to use a helper account.');return helpers[i].connect(provider);}
async function receipt(hash){let r=await provider.getTransactionReceipt(hash);if(!r){say('Waiting for the previous transaction to confirm…');r=await provider.waitForTransaction(hash,1,180000);}if(!r)throw Error('Not confirmed yet. Resume later.');if(r.status!==1)throw Error('The previous transaction failed. Inspect it in the block explorer.');return r;}
async function deploy(){await guardNetwork();if(connected?.toLowerCase()!==OWNER.toLowerCase())throw Error('Deployment must be signed by the designated owner wallet.');if(!state.config||!state.encrypted||!$('backup-confirm').checked)throw Error('Prepare test accounts and confirm that you saved the encrypted backup.');
 for(let i=0;i<5;i++){
  const current=state.steps[i];if(current?.hash){const prior=await provider.getTransactionReceipt(current.hash);if(prior&&prior.status===0){state.steps.splice(i);save();throw Error('Failed deployment cleared. Resume to retry this step.');}const r=await receipt(current.hash);const tx=await provider.getTransaction(current.hash);if(tx.from.toLowerCase()!==OWNER.toLowerCase()||tx.to!==null||!tx.data.startsWith(artifacts[names[i]].bytecode))throw Error('Saved transaction does not match the expected contract.');state.steps[i]={...current,address:r.contractAddress,status:'confirmed'};save();continue;}
  const args=i===0?[]:i===1?[state.config.owners]:i===2?[state.steps[1].address]:i===3?[state.steps[0].address,state.steps[2].address,state.steps[1].address]:[state.steps[0].address,state.steps[3].address,state.steps[2].address,state.steps[1].address,OWNER,state.config.genesis];
  say(`Step ${i+1} of 6: ${labels[i]} — review and approve in your wallet.`);
  const factory=new ContractFactory(artifacts[names[i]].abi,artifacts[names[i]].bytecode,mainSigner);const c=await factory.deploy(...args);const hash=c.deploymentTransaction().hash;state.steps[i]={hash,address:c.target,status:'pending'};save();const r=await receipt(hash);state.steps[i]={hash,address:r.contractAddress,status:'confirmed'};save();
 }
 const token=getContract(3,mainSigner);const bound=await token.binary();if(bound.toLowerCase()!==state.steps[4].address.toLowerCase()){
  if(bound!=='0x0000000000000000000000000000000000000000')throw Error('The token is bound to a different contract.');
  if(state.steps[5]?.hash){const prior=await provider.getTransactionReceipt(state.steps[5].hash);if(prior&&prior.status===0){state.steps.splice(5);save();throw Error('Failed connection cleared. Resume to retry.');}await receipt(state.steps[5].hash);}else{say('Step 6 of 6: approve the contract connection.');const tx=await token.bind(state.steps[4].address);state.steps[5]={hash:tx.hash,status:'pending'};save();await receipt(tx.hash);}
 }
 if((await token.binary()).toLowerCase()!==state.steps[4].address.toLowerCase())throw Error('Connection could not be verified.');state.steps[5]={...state.steps[5],status:'confirmed'};save();download('FTI-Testnet-Deployment.json',{version:1,owner:OWNER,chainId:97,config:state.config,steps:state.steps});showTab('test');
}
async function send(txPromise){const tx=await txPromise;say('Transaction submitted: '+tx.hash);await tx.wait();return tx.hash;}
async function approvedUSD(signer,spender,amount){const usd=getContract(0,signer),address=await signer.getAddress();if(await usd.allowance(address,spender)<amount)await send(usd.approve(spender,amount));}
async function refresh(){if(!provider)return;await guardNetwork();$('wallet').textContent=`${connected} · Balance: ${fmt(await provider.getBalance(connected))} tBNB`;if(state.steps[5]?.status!=='confirmed')return;
 const i=$('account').value;const who=i==='owner'?connected:state.config.genesis[Number(i)+1];const b=getContract(4),t=getContract(3),usd=getContract(0);
 const [m,balance,fti,unlocked,reward,price,reserve,epoch,end,phase,jobCursor,jobs,auto,bnb]=await Promise.all([b.members(who),usd.balanceOf(who),t.balanceOf(who),t.unlocked(who),b.pendingReward(who),t.price(),t.reserve(),b.epoch(),b.epochEnd(),b.phase(),b.jobCursor(),b.jobCount(),b.pendingAuto(who),provider.getBalance(who)]);
 $('price').textContent=fmt(price);$('reserve').textContent=fmt(reserve);$('reward').textContent=fmt(reward);$('account-info').textContent=`${who} | Gas ${fmt(bnb)} tBNB | USD ${fmt(balance)} | FTI ${fmt(fti)} | Unlocked ${fmt(unlocked)} | Units ${m.units} | Rank ${m.rank} | Pending auto-buy ${fmt(auto)}`;
 $('settlement').textContent=`Epoch ${epoch} · Phase ${phase} · Volume queue ${jobCursor}/${jobs} · Epoch end ${new Date(Number(end)*1000).toLocaleString('en-US')}`;
 $('gov-status').textContent=`Proposal count: ${await getContract(1).count()}`;
}
function showTab(id){document.querySelectorAll('.tab').forEach(e=>e.hidden=e.id!==id);document.querySelectorAll('[data-tab]').forEach(e=>e.classList.toggle('selected',e.dataset.tab===id));}
document.querySelectorAll('[data-tab]').forEach(e=>e.onclick=()=>showTab(e.dataset.tab));
$('connect').onclick=()=>action(connect);$('refresh').onclick=()=>action(refresh);$('account').onchange=()=>action(refresh);
$('generate').onclick=()=>action(async()=>{await guardNetwork();if(connected.toLowerCase()!==OWNER.toLowerCase())throw Error('Connect the owner wallet.');if(state.steps.length||state.config)throw Error('Accounts already exist. Restore the existing backup to preserve access.');const password=$('password').value;if(password.length<12)throw Error('Use a password of at least 12 characters.');say('Creating accounts and encrypting the backup in your browser…');helpers=Array.from({length:30},()=>Wallet.createRandom());state.config={genesis:[OWNER,...helpers.map(w=>w.address)],owners:[OWNER,...helpers.slice(0,4).map(w=>w.address)]};state.encrypted=await encrypt({privateKeys:helpers.map(w=>w.privateKey),config:state.config},password);$('password').value='';save();download('FTI-Testnet-Encrypted-Backup.json',state.encrypted);});
$('restore').onchange=e=>action(async()=>{if(!e.target.files[0])return;const file=e.target.files[0];if(file.size>200000)throw Error('File is too large.');const data=JSON.parse(await file.text());const plain=await decrypt(data,$('password').value);const wallets=plain.privateKeys.map(k=>new Wallet(k));if(wallets.length!==30||new Set(wallets.map(w=>w.address)).size!==30)throw Error('Backup accounts are invalid.');const expected={genesis:[OWNER,...wallets.map(w=>w.address)],owners:[OWNER,...wallets.slice(0,4).map(w=>w.address)]};if(JSON.stringify(expected)!==JSON.stringify(plain.config))throw Error('Addresses do not match the backup keys.');if(state.config&&JSON.stringify(state.config)!==JSON.stringify(expected))throw Error('This backup belongs to another deployment.');helpers=wallets;state.config=expected;state.encrypted=data;$('password').value='';save();});
$('download-backup').onclick=()=>action(async()=>{if(!state.encrypted)throw Error('No encrypted backup yet.');download('FTI-Testnet-Encrypted-Backup.json',state.encrypted);});
$('deploy').onclick=()=>action(deploy);$('export').onclick=()=>download('FTI-Testnet-Deployment.json',{version:1,owner:OWNER,chainId:97,config:state.config,steps:state.steps});
$('import-deployment').onchange=e=>action(async()=>{if(!e.target.files[0])return;const file=e.target.files[0];if(file.size>200000)throw Error('File is too large.');const data=JSON.parse(await file.text());if(data.owner!==OWNER||data.chainId!==97||data.version!==1||!Array.isArray(data.steps)||data.steps.length>6||data.config?.genesis?.length!==31||data.config?.owners?.length!==5)throw Error('Invalid deployment file.');if(state.config&&JSON.stringify(state.config)!==JSON.stringify(data.config))throw Error('Account backup does not match.');await guardNetwork();for(let i=0;i<data.steps.length;i++){const item=data.steps[i];if(!/^0x[0-9a-fA-F]{64}$/.test(item.hash||''))throw Error('Invalid transaction hash.');const tx=await provider.getTransaction(item.hash);if(!tx||tx.from.toLowerCase()!==OWNER.toLowerCase())throw Error('Owner transaction not found.');if(i<5&&(!tx.data.startsWith(artifacts[names[i]].bytecode)||tx.to!==null))throw Error('Contract bytecode does not match.');const r=await receipt(item.hash);if(i<5&&r.contractAddress.toLowerCase()!==item.address.toLowerCase())throw Error('Contract address does not match.');}state.config=data.config;state.steps=data.steps;save();});
$('fund-gas').onclick=()=>action(async()=>{await guardNetwork();if(connected.toLowerCase()!==OWNER.toLowerCase()||$('account').value==='owner')throw Error('Connect the owner wallet and select a helper account.');const to=state.config.genesis[Number($('account').value)+1];if(!confirm(`Send 0.01 test tBNB to ${to}?`))return;await send(mainSigner.sendTransaction({to,value:parseEther('0.01')}));});
$('faucet').onclick=()=>action(async()=>send(getContract(0,await accountSigner()).faucet()));
$('add-units').onclick=()=>action(async()=>{const n=BigInt($('units').value);if(n<1n||n>1000000n)throw Error('Invalid unit count.');const signer=await accountSigner();await approvedUSD(signer,state.steps[4].address,n*parseEther('100'));await send(getContract(4,signer).addUnits(n));});
$('register').onclick=()=>action(async()=>{const n=BigInt($('units').value),parent=$('sponsor').value;if(n<1n||n>1000000n||!isAddress(parent))throw Error('Invalid units or sponsor.');const signer=await accountSigner();await approvedUSD(signer,state.steps[4].address,n*parseEther('100'));await send(getContract(4,signer).register(parent,n));});
$('claim').onclick=()=>action(async()=>send(getContract(4,await accountSigner()).claim()));
$('buy').onclick=()=>action(async()=>{const signer=await accountSigner(),amount=parseEther($('buy-amount').value);if(amount<=0n)throw Error('Invalid amount.');const t=getContract(3,signer),quote=await t.quoteBuy(amount);$('quote').textContent=`Estimated output: ${fmt(quote)} FTI`;if(!confirm(`Buy approximately ${fmt(quote)} FTI with ${fmt(amount)} test USD? Tokens will be locked.`))return;await approvedUSD(signer,state.steps[3].address,amount);const block=await provider.getBlock('latest');await send(t.buy(amount,quote*995n/1000n,block.timestamp+1200));});
$('sell').onclick=()=>action(async()=>{const signer=await accountSigner(),amount=parseEther($('sell-amount').value);if(amount<=0n)throw Error('Invalid amount.');const t=getContract(3,signer),[quote,fee]=await t.quoteSell(amount);$('quote').textContent=`Net proceeds: ${fmt(quote)} test USD · Fee ${Number(fee)/100}%`;if(!confirm(`Sell ${fmt(amount)} FTI for approximately ${fmt(quote)} test USD?`))return;const block=await provider.getBlock('latest');await send(t.sell(amount,quote*995n/1000n,block.timestamp+1200));});
for(const[id,method,arg]of [['volume','processVolume',50],['close','beginEpochClose'],['process','processEpoch',50],['month','beginBuilderMonth'],['month-process','processBuilderMonth',50]])$(id).onclick=()=>action(async()=>send(getContract(4,await accountSigner())[method](...(arg?[arg]:[]))));
$('auto-on').onclick=()=>action(async()=>send(getContract(4,await accountSigner()).setAutoBuy(true,parseEther($('auto-price').value))));$('auto-off').onclick=()=>action(async()=>send(getContract(4,await accountSigner()).setAutoBuy(false,0)));$('auto-cash').onclick=()=>action(async()=>send(getContract(4,await accountSigner()).releaseAutoToCash()));$('auto-run').onclick=()=>action(async()=>{const signer=await accountSigner(),who=await signer.getAddress(),b=getContract(4,signer);await send(b.executeAuto(who,await b.pendingAuto(who)));});
$('propose').onclick=()=>action(async()=>{const signer=await accountSigner(),choice=$('gov-action').value,index=choice.includes('Binary')?4:3;let target=state.steps[index].address,data=getContract(index).interface.encodeFunctionData(choice.startsWith('unpause')?'unpause':'pause');if(choice.startsWith('unpause')){data=getContract(2).interface.encodeFunctionData('schedule',[target,0,data,ZeroHash,hexlify(randomBytes(32)),259200]);target=state.steps[2].address;}await send(getContract(1,signer).propose(target,data));});
$('vote').onclick=()=>action(async()=>send(getContract(1,await accountSigner()).approve(BigInt($('proposal-id').value))));$('execute-proposal').onclick=()=>action(async()=>send(getContract(1,await accountSigner()).execute(BigInt($('proposal-id').value))));$('execute-delayed').onclick=()=>action(async()=>{const signer=await accountSigner(),p=await getContract(1).proposal(BigInt($('proposal-id').value));if(!p[3]||p[0].toLowerCase()!==state.steps[2].address.toLowerCase())throw Error('Invalid scheduling proposal.');const args=getContract(2).interface.decodeFunctionData('schedule',p[1]);await send(getContract(2,signer).execute(args[0],args[1],args[2],args[3],args[4]));});
window.ethereum?.on?.('accountsChanged',()=>{provider=null;mainSigner=null;connected=null;say('Account changed. Reconnect your wallet.');render();});window.ethereum?.on?.('chainChanged',()=>{if(!busy){provider=null;mainSigner=null;say('Network changed. Reconnect your wallet.');}});
const context=document.modelContext;if(context?.registerTool){const life=new AbortController();Promise.resolve(context.registerTool({name:'read_fti_deployment_status',description:'Read public testnet deployment progress; never reads or returns keys or encrypted backups.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:input=>{if(!input||Object.keys(input).length)throw Error('No arguments allowed');return{chainId:97,owner:OWNER,steps:state.steps.map((s,i)=>({name:labels[i],status:s.status,address:s.address||null,hash:s.hash||null}))};}},{signal:life.signal})).catch(()=>{});window.addEventListener('pagehide',()=>life.abort(),{once:true});}
render();if(state.steps.some(s=>s.status==='confirmed'))say('Saved progress loaded. Connect your wallet to verify it on-chain.');
